"""
Sprint: Bellissima Ground Truth Foundation.

Proves the end-to-end path PDF -> Artifact -> Statement -> Review -> Truth
Engine -> Passenger Answer, and that nothing bypasses it.

The PDF used is a fixture generated by the test. Its digest is genuinely
computed from real bytes; it makes no claim about any vessel. When the first
Bellissima document is acquired it is imported by the same call.
"""

import os
import shutil
import tempfile
import unittest

from timonelo.evidence import authority
from timonelo.evidence.editor import EditorError, StatementEditor
from timonelo.evidence.importer import ImportError_, import_pdf
from timonelo.evidence.questions import Question, QuestionRegistry
from timonelo.evidence.registry import ArtifactRegistry, RegistryError
from timonelo.evidence.review import ReviewError, ReviewLog
from timonelo.evidence.truth import TruthEngine
from timonelo.ontology.models import HumanReviewState, PublishStatus

FIXTURE_CLASS = "pipeline_fixture"
FIXTURE_TYPE = "fixture.deck"


def _write_pdf(path: str, text: str = "TIMONELO FIXTURE - NOT A SHIP DOCUMENT") -> str:
    content = f"BT /F1 12 Tf 40 700 Td ({text}) Tj ET"
    objs = [
        "<< /Type /Catalog /Pages 2 0 R >>",
        "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Contents 4 0 R "
        "/Resources << /Font << /F1 5 0 R >> >> >>",
        f"<< /Length {len(content)} >>\nstream\n{content}\nendstream",
        "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    ]
    out, offsets = "%PDF-1.4\n", []
    for i, o in enumerate(objs, 1):
        offsets.append(len(out))
        out += f"{i} 0 obj\n{o}\nendobj\n"
    xref = len(out)
    out += f"xref\n0 {len(objs) + 1}\n0000000000 65535 f \n"
    for off in offsets:
        out += f"{off:010d} 00000 n \n"
    out += (f"trailer\n<< /Size {len(objs) + 1} /Root 1 0 R >>\n"
            f"startxref\n{xref}\n%%EOF\n")
    with open(path, "w", encoding="latin-1") as f:
        f.write(out)
    return path


class PipelineCase(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        authority.DOCUMENT_CLASSES.setdefault(FIXTURE_CLASS, authority.DocumentClass(
            FIXTURE_CLASS, "Pipeline fixture", 0.80,
            authority.ValidityScope.STRUCTURAL, authority.Acquisition.PUBLIC,
            authority.UsePermission.CITE_AND_STORE))
        authority.AUTHORITY.setdefault(FIXTURE_TYPE, (FIXTURE_CLASS,))

    def setUp(self):
        # authority.AUTHORITY and DOCUMENT_CLASSES are module-global and are
        # mutated by workspace loading. Without snapshot/restore, fixtures from
        # one test file silently overwrite another's entries.
        self._AUTH_SNAPSHOT = dict(authority.AUTHORITY)
        self._CLASS_SNAPSHOT = dict(authority.DOCUMENT_CLASSES)
        self.tmp = tempfile.mkdtemp()
        self.pdf = _write_pdf(os.path.join(self.tmp, "fixture.pdf"))
        self.registry = ArtifactRegistry(os.path.join(self.tmp, "artifacts"))
        self.reviews = ReviewLog(os.path.join(self.tmp, "reviews.json"))
        self.editor = StatementEditor(
            os.path.join(self.tmp, "statements.json"), self.registry, self.reviews)
        self.questions = QuestionRegistry("test")
        self.questions.register(Question(
            "Q-0001", "fixture", statement_type=FIXTURE_TYPE,
            labels={"en": "Which deck?"},
            unknown_guidance="Timonelo holds no source for this yet."))
        self.engine = TruthEngine(self.questions, self.editor, self.registry)

    def tearDown(self):
        authority.AUTHORITY.clear(); authority.AUTHORITY.update(self._AUTH_SNAPSHOT)
        authority.DOCUMENT_CLASSES.clear()
        authority.DOCUMENT_CLASSES.update(self._CLASS_SNAPSHOT)
        shutil.rmtree(self.tmp, ignore_errors=True)

    def _import(self):
        return import_pdf(
            self.registry, self.pdf, document_class=FIXTURE_CLASS,
            acquired_on="2026-08-17", acquisition_method="test fixture",
            publisher="Timonelo", published_on="2026-08-17",
            version="1", language="en")

    def _draft(self, artifact):
        return self.editor.create(
            entity_id="fixture:1", question_id="Q-0001",
            statement_type=FIXTURE_TYPE, value=14,
            artifact_id=artifact.artifact_id, page=1, locator="page 1",
            read_by="reader.one", read_on="2026-08-17")

    def _publish(self, s):
        s = self.editor.transition(s.statement_id, HumanReviewState.UNDER_REVIEW,
                                   "reader.one", "2026-08-17")
        s = self.editor.transition(s.statement_id, HumanReviewState.APPROVED,
                                   "reviewer.two", "2026-08-17")
        return self.editor.publish(s.statement_id, "reviewer.two", "2026-08-17")


class TestEmptyStore(PipelineCase):

    def test_store_starts_empty(self):
        self.assertEqual(len(self.registry), 0)
        self.assertEqual(len(self.editor), 0)

    def test_empty_engine_answers_unknown(self):
        ans = self.engine.answer("fixture:1", "Q-0001")
        self.assertFalse(ans.known)
        self.assertIsNone(ans.value)
        self.assertIn("no source", ans.unknown_guidance)

    def test_coverage_is_zero(self):
        self.assertEqual(
            self.engine.coverage("fixture:1", "fixture")["coverage"], 0.0)


class TestImporter(PipelineCase):

    def test_digest_computed_from_real_bytes(self):
        import hashlib
        art = self._import()
        with open(self.pdf, "rb") as f:
            self.assertEqual(art.sha256, hashlib.sha256(f.read()).hexdigest())

    def test_rejects_non_pdf(self):
        bad = os.path.join(self.tmp, "not.pdf")
        with open(bad, "w") as f:
            f.write("plain text pretending to be a PDF")
        with self.assertRaises(ImportError_):
            import_pdf(self.registry, bad, FIXTURE_CLASS, "2026-08-17", "test")

    def test_rejects_missing_file(self):
        with self.assertRaises(ImportError_):
            import_pdf(self.registry, os.path.join(self.tmp, "nope.pdf"),
                       FIXTURE_CLASS, "2026-08-17", "test")

    def test_rejects_undeclared_document_class(self):
        with self.assertRaises(RegistryError):
            import_pdf(self.registry, self.pdf, "passenger_blog",
                       "2026-08-17", "test")

    def test_importer_creates_no_statements(self):
        """The importer ends at registration."""
        self._import()
        self.assertEqual(len(self.editor), 0)

    def test_same_bytes_do_not_get_a_second_id(self):
        a = self._import()
        b = self._import()
        self.assertEqual(a.artifact_id, b.artifact_id)
        self.assertEqual(len(self.registry), 1)

    def test_ids_are_issued_sequentially_and_immutably(self):
        a = self._import()
        other = _write_pdf(os.path.join(self.tmp, "other.pdf"), "DIFFERENT")
        b = import_pdf(self.registry, other, FIXTURE_CLASS, "2026-08-17", "test")
        self.assertEqual(a.artifact_id, "ART-0001")
        self.assertEqual(b.artifact_id, "ART-0002")

    def test_verify_detects_substitution(self):
        art = self._import()
        with open(self.registry.blob_path(art.artifact_id), "w") as f:
            f.write("substituted")
        self.assertFalse(self.registry.verify(art.artifact_id))


class TestStatementEditor(PipelineCase):

    def test_statement_requires_held_artifact(self):
        with self.assertRaises(RegistryError):
            self.editor.create(
                entity_id="fixture:1", question_id="Q-0001",
                statement_type=FIXTURE_TYPE, value=14, artifact_id="ART-9999",
                locator="p1", read_by="r", read_on="2026-08-17")

    def test_statement_requires_locator(self):
        art = self._import()
        with self.assertRaises(EditorError):
            self.editor.create(
                entity_id="fixture:1", question_id="Q-0001",
                statement_type=FIXTURE_TYPE, value=14,
                artifact_id=art.artifact_id, locator="",
                read_by="r", read_on="2026-08-17")

    def test_statement_requires_reader_and_date(self):
        art = self._import()
        with self.assertRaises(EditorError):
            self.editor.create(
                entity_id="fixture:1", question_id="Q-0001",
                statement_type=FIXTURE_TYPE, value=14,
                artifact_id=art.artifact_id, locator="p1",
                read_by="", read_on="2026-08-17")

    def test_authority_matrix_is_enforced_at_creation(self):
        art = self._import()
        with self.assertRaises(authority.AuthorityError):
            self.editor.create(
                entity_id="cabin:X", question_id="Q-0001",
                statement_type="cabin.area_sqm", value=19.0,
                artifact_id=art.artifact_id, locator="p1",
                read_by="r", read_on="2026-08-17")

    def test_statement_starts_in_draft(self):
        s = self._draft(self._import())
        self.assertEqual(s.state, HumanReviewState.DRAFT)


class TestReviewWorkflow(PipelineCase):

    def test_draft_cannot_be_published_directly(self):
        s = self._draft(self._import())
        with self.assertRaises(EditorError):
            self.editor.publish(s.statement_id, "reviewer.two", "2026-08-17")

    def test_draft_cannot_jump_to_approved(self):
        s = self._draft(self._import())
        with self.assertRaises(ReviewError):
            self.editor.transition(s.statement_id, HumanReviewState.APPROVED,
                                   "reviewer.two", "2026-08-17")

    def test_reader_cannot_publish_own_statement(self):
        s = self._draft(self._import())
        s = self.editor.transition(s.statement_id, HumanReviewState.UNDER_REVIEW,
                                   "reader.one", "2026-08-17")
        s = self.editor.transition(s.statement_id, HumanReviewState.APPROVED,
                                   "reviewer.two", "2026-08-17")
        with self.assertRaises(EditorError):
            self.editor.publish(s.statement_id, "reader.one", "2026-08-17")

    def test_transition_requires_named_actor(self):
        s = self._draft(self._import())
        with self.assertRaises(ReviewError):
            self.editor.transition(s.statement_id, HumanReviewState.UNDER_REVIEW,
                                   "", "2026-08-17")

    def test_rejected_is_terminal(self):
        s = self._draft(self._import())
        s = self.editor.transition(s.statement_id, HumanReviewState.UNDER_REVIEW,
                                   "reader.one", "2026-08-17")
        s = self.editor.transition(s.statement_id, HumanReviewState.REJECTED,
                                   "reviewer.two", "2026-08-17")
        with self.assertRaises(ReviewError):
            self.editor.transition(s.statement_id, HumanReviewState.APPROVED,
                                   "reviewer.two", "2026-08-17")

    def test_history_records_actor_and_date(self):
        s = self._publish(self._draft(self._import()))
        hist = self.reviews.history(s.statement_id)
        self.assertEqual(len(hist), 2)
        self.assertEqual(hist[-1].to_state, "APPROVED")
        self.assertEqual(hist[-1].actor, "reviewer.two")


class TestTruthEngineVisibility(PipelineCase):

    def test_draft_never_reaches_a_passenger(self):
        self._draft(self._import())
        self.assertFalse(self.engine.answer("fixture:1", "Q-0001").known)

    def test_under_review_never_reaches_a_passenger(self):
        s = self._draft(self._import())
        self.editor.transition(s.statement_id, HumanReviewState.UNDER_REVIEW,
                               "reader.one", "2026-08-17")
        self.assertFalse(self.engine.answer("fixture:1", "Q-0001").known)

    def test_approved_without_publish_is_not_answerable(self):
        s = self._draft(self._import())
        s = self.editor.transition(s.statement_id, HumanReviewState.UNDER_REVIEW,
                                   "reader.one", "2026-08-17")
        self.editor.transition(s.statement_id, HumanReviewState.APPROVED,
                               "reviewer.two", "2026-08-17")
        # In blocked publication status, answer is not known to passengers
        self.assertFalse(self.engine.answer("fixture:1", "Q-0001").known)

    def test_published_is_answerable(self):
        s = self._draft(self._import())
        s = self.editor.transition(s.statement_id, HumanReviewState.UNDER_REVIEW,
                                   "reader.one", "2026-08-17")
        self.editor.transition(s.statement_id, HumanReviewState.APPROVED,
                               "reviewer.two", "2026-08-17")
        self.editor.publish(s.statement_id, "reviewer.two", "2026-08-17")
        self.assertTrue(self.engine.answer("fixture:1", "Q-0001").known)

    def test_rejected_is_not_answerable(self):
        s = self._publish(self._draft(self._import()))
        self.editor.transition(s.statement_id, HumanReviewState.REJECTED,
                               "reviewer.two", "2026-08-18")
        self.assertFalse(self.engine.answer("fixture:1", "Q-0001").known)


class TestEndToEnd(PipelineCase):

    def test_full_chain_produces_a_traceable_answer(self):
        art = self._import()
        self._publish(self._draft(art))
        ans = self.engine.answer("fixture:1", "Q-0001")

        self.assertTrue(ans.known)
        self.assertEqual(ans.value, 14)
        p = ans.provenance
        self.assertEqual(p.artifact_id, art.artifact_id)
        self.assertEqual(p.page, 1)
        self.assertEqual(p.read_by, "reader.one")
        self.assertEqual(p.document_class, FIXTURE_CLASS)
        # The artifact behind the answer is still the bytes we hashed.
        self.assertTrue(self.registry.verify(art.artifact_id))

    def test_confidence_is_computed_not_stored(self):
        art = self._import()
        s = self._publish(self._draft(art))
        self.assertFalse(hasattr(s, "confidence"))
        self.assertEqual(
            self.engine.confidence(s),
            authority.reliability_of(FIXTURE_CLASS))

    def test_confidence_never_reaches_certainty(self):
        self._publish(self._draft(self._import()))
        self.assertLess(self.engine.answer("fixture:1", "Q-0001").confidence, 1.0)

    def test_unanswered_question_stays_unknown(self):
        self._publish(self._draft(self._import()))
        ans = self.engine.answer("fixture:2", "Q-0001")
        self.assertFalse(ans.known)


if __name__ == "__main__":
    unittest.main()
