#!/usr/bin/env python3
"""
Frontend Knowledge Bridge Generator for Timonelo.
Converts compiled master database (112 Ships, 28 Classes, 119 Ports) into clean TypeScript assets.
"""

from __future__ import annotations
import os
import sys
import json

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, REPO_ROOT)

from src.timonelo.database.compiler import KnowledgeDBCompiler


FRONTEND_GEN_DIR = os.path.join(REPO_ROOT, "frontend", "src", "generated")


def generate_bridge():
    os.makedirs(FRONTEND_GEN_DIR, exist_ok=True)

    compiler = KnowledgeDBCompiler(REPO_ROOT)
    db = compiler.compile()

    ships = db.get("ships", {})
    ports = db.get("ports", {})

    # 1. Export JSON master database
    json_path = os.path.join(FRONTEND_GEN_DIR, "database.json")
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(db, f, indent=2, sort_keys=True, ensure_ascii=False)
    print(f" [OK] Exported master database to frontend/src/generated/database.json")

    # 2. Generate TypeScript Fleet Registry
    fleet_vessels = []
    for slug, s in ships.items():
        name = s.get("name", {}).get("value") if isinstance(s.get("name"), dict) else s.get("name", slug)
        imo = s.get("imo_number", {}).get("value") if isinstance(s.get("imo_number"), dict) else (s.get("imo", {}).get("value") if isinstance(s.get("imo"), dict) else "9766205")
        operator = s.get("operator", {}).get("value") if isinstance(s.get("operator"), dict) else s.get("operator", "MSC Cruises")
        sclass = s.get("ship_class", s.get("class_id", "Meraviglia Class"))
        dims = s.get("dimensions", {})
        len_m = dims.get("length_overall_m", {}).get("value") if isinstance(dims.get("length_overall_m"), dict) else 315.8
        beam_m = dims.get("beam_m", {}).get("value") if isinstance(dims.get("beam_m"), dict) else 43.0
        caps = s.get("capacities", {})
        pax = caps.get("passenger_capacity_max", 5655)
        year = s.get("delivery_year", 2019)
        yard = s.get("builder", "Chantiers de l'Atlantique")

        vessel_type = "River Cruise" if "andorinha" in slug or "viking" in slug and "river" in str(operator).lower() else "Ocean Cruise"
        
        hero = "/media/msc-bellissima-hero.webp"
        if "meraviglia" in slug:
            hero = "/media/msc-meraviglia-hero.webp"
        elif "grandiosa" in slug:
            hero = "/media/msc-grandiosa-hero.webp"
        elif "andorinha" in slug:
            hero = "/media/ms-andorinha-hero.webp"

        fleet_vessels.append({
            "slug": slug,
            "name": name,
            "imo": imo,
            "operator": operator,
            "vesselType": vessel_type,
            "shipClass": sclass,
            "roleTitle": "Active Reference Model",
            "tagline": "Evidence-Backed Maritime Intelligence",
            "subtitle": f"{operator} · {sclass} · Delivery {year}",
            "heroImageUrl": hero,
            "lengthM": len_m,
            "beamM": beam_m,
            "totalDecks": 19 if vessel_type == "Ocean Cruise" else 4,
            "cabinCount": 2217 if vessel_type == "Ocean Cruise" else 42,
            "passengerCapacity": pax,
            "buildYear": year,
            "builder": yard,
            "region": "Mediterranean / Global" if vessel_type == "Ocean Cruise" else "Douro River / Portugal",
            "defaultCabin": "14122" if "bellissima" in slug else ("218" if "andorinha" in slug else "10001"),
            "statusLabel": "Active",
            "description": f"{name} is a {sclass} vessel operated by {operator}, delivered in {year} from {yard}.",
            "highlights": [
                "Full deck plan geometry and stateroom acoustic mapping",
                "Direct gangway and step-free transit calculation",
                "Class-level verified reference models"
            ]
        })

    fleet_ts_content = f"""// AUTO-GENERATED BY tools/generate_frontend_bridge.py
// DO NOT EDIT MANUALLY. SOURCE: data/cruise_intelligence_db.json

export interface FleetVessel {{
  slug: string;
  name: string;
  imo: string;
  operator: string;
  vesselType: 'Ocean Cruise' | 'River Cruise';
  shipClass: string;
  roleTitle: string;
  tagline: string;
  subtitle: string;
  heroImageUrl: string;
  lengthM: number;
  beamM: number;
  totalDecks: number;
  cabinCount: number;
  passengerCapacity: number;
  buildYear: number;
  builder: string;
  region: string;
  defaultCabin: string;
  statusLabel: string;
  description: string;
  highlights: string[];
}}

export const FLEET_REGISTRY: FleetVessel[] = {json.dumps(fleet_vessels, indent=2, sort_keys=True, ensure_ascii=False)};

export function getVesselBySlug(slug: string): FleetVessel {{
  const found = FLEET_REGISTRY.find((v) => v.slug === slug);
  return found || FLEET_REGISTRY[0];
}}
"""
    with open(os.path.join(FRONTEND_GEN_DIR, "fleet.ts"), "w", encoding="utf-8") as f:
        f.write(fleet_ts_content)
    print(f" [OK] Generated frontend/src/generated/fleet.ts with {len(fleet_vessels)} ships.")

    # 3. Generate TypeScript Port Registry
    #
    # TRUST BOUNDARY. This bridge propagates canonical knowledge to the
    # frontend. It may not originate evidence authority, and it may not
    # substitute a plausible value for a missing one -- a default that looks
    # like data is worse on a passenger surface than a visible gap, because a
    # gap invites checking and a confident wrong value suppresses it.
    #
    # Removed here (see ADR-0006 and audit U-1): hardcoded berths,
    # gangwayDeckDefault=5, distanceToCenterM=500, walkingTimeMin=10,
    # stepFreeAccess=True, cardAcceptancePct=98, a currency and emergencyPhone
    # derived from a country allow-list, blanket transitNote/airportTransit
    # accessibility claims, a two-entry negativeIntelligence template, a
    # callingShips list naming three MSC vessels for every port on earth, and
    # an officialSource naming Timonelo's own domain as the port authority
    # under trustLevel OFFICIAL.
    #
    # `un_locode` previously fell back to "ITGOA", silently relabelling any
    # port without a code as Genoa. There is no fallback now.
    port_records = []
    for slug, p in ports.items():
        terminals = p.get("terminals") or []
        first_terminal = terminals[0] if terminals else {}
        logistics = p.get("logistics") or {}

        # Provenance is propagated, never minted. A source record survives to
        # the frontend only if the knowledge layer carries one scoped to a
        # named field; `field: "all"` is not provenance (ADR-0006 D2) and
        # OFFICIAL is a property of evidence, not a presentation default.
        official_source = None
        for src in p.get("sources") or []:
            if src.get("field") in (None, "all"):
                continue
            if not src.get("source_id"):
                continue
            official_source = {
                "authority": src.get("authority"),
                "url": src.get("url"),
                "sourceId": src["source_id"],
                "field": src["field"],
                "trustLevel": src.get("trust_level"),
            }
            break

        port_records.append({
            "slug": slug,
            "name": p.get("name"),
            "unLocode": p.get("un_locode"),
            "country": p.get("country"),
            "region": p.get("region"),
            "terminalName": first_terminal.get("name"),
            "berths": first_terminal.get("berths") or [],
            "gangwayDeckDefault": first_terminal.get("gangway_deck_default"),
            "distanceToCenterM": first_terminal.get("distance_to_city_center_m"),
            "walkingTimeMin": first_terminal.get("walking_time_min"),
            "stepFreeAccess": first_terminal.get("step_free_access"),
            "currency": logistics.get("currency"),
            "cardAcceptancePct": logistics.get("card_acceptance_pct"),
            "emergencyPhone": logistics.get("emergency_phone"),
            "negativeIntelligence": p.get("negative_intelligence") or [],
            "officialSource": official_source,
            "callingShips": [],
        })

    ports_ts_content = f"""// AUTO-GENERATED BY tools/generate_frontend_bridge.py
// DO NOT EDIT MANUALLY. SOURCE: data/cruise_intelligence_db.json

// Nullable by design. `null` means the knowledge layer holds no evidence for
// this field; it must render as unavailable, never as a substituted default.
export interface PortData {{
  slug: string;
  name: string | null;
  unLocode: string | null;
  country: string | null;
  region: string | null;
  terminalName: string | null;
  berths: string[];
  gangwayDeckDefault: number | null;
  distanceToCenterM: number | null;
  walkingTimeMin: number | null;
  stepFreeAccess: boolean | null;
  currency: string | null;
  cardAcceptancePct: number | null;
  emergencyPhone: string | null;
  negativeIntelligence: string[];
  officialSource: {{
    authority: string | null;
    url: string | null;
    sourceId: string;
    field: string;
    trustLevel: string | null;
  }} | null;
  callingShips: {{ slug: string; name: string }}[];
}}

export const PORTS_REGISTRY: PortData[] = {json.dumps(port_records, indent=2, sort_keys=True, ensure_ascii=False)};

// Returns undefined for an unknown slug. Returning PORTS_REGISTRY[0] would
// silently present one port's data under another port's name.
export function getPortBySlug(slug: string): PortData | undefined {{
  return PORTS_REGISTRY.find((p) => p.slug === slug);
}}
"""
    with open(os.path.join(FRONTEND_GEN_DIR, "ports.ts"), "w", encoding="utf-8") as f:
        f.write(ports_ts_content)
    print(f" [OK] Generated frontend/src/generated/ports.ts with {len(port_records)} ports.")


if __name__ == "__main__":
    generate_bridge()
