#!/usr/bin/env python3
"""
Frontend Knowledge Bridge Generator for Timonelo.
Converts compiled master database (112 Ships, 28 Classes, 119 Ports) into TypeScript assets.
"""

from __future__ import annotations
import os
import sys
import json

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, REPO_ROOT)

from src.timonelo.database.compiler import KnowledgeDBCompiler
from src.timonelo.database.cruise_dna import CANONICAL_GENOMES
from src.timonelo.database.decision_engine import DecisionEngine


FRONTEND_GEN_DIR = os.path.join(REPO_ROOT, "frontend", "src", "generated")


def generate_bridge():
    os.makedirs(FRONTEND_GEN_DIR, exist_ok=True)

    compiler = KnowledgeDBCompiler(REPO_ROOT)
    db = compiler.compile()

    ships = db.get("ships", {})
    ports = db.get("ports", {})
    classes = db.get("ship_classes", {})

    # 1. Export JSON master database
    json_path = os.path.join(FRONTEND_GEN_DIR, "database.json")
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(db, f, indent=2, ensure_ascii=False)
    print(f" [OK] Exported master database to frontend/src/generated/database.json")

    # 2. Generate TypeScript Fleet Registry
    fleet_vessels = []
    for slug, s in ships.items():
        name = s.get("name", {}).get("value") if isinstance(s.get("name"), dict) else s.get("name", slug)
        imo = s.get("imo_number", {}).get("value") if isinstance(s.get("imo_number"), dict) else (s.get("imo", {}).get("value") if isinstance(s.get("imo"), dict) else "9766205")
        operator = s.get("operator", {}).get("value") if isinstance(s.get("operator"), dict) else s.get("operator", "MSC Cruises")
        sclass = s.get("ship_class", s.get("class_id", "Meraviglia Class"))
        dims = s.get("dimensions", {})
        gt = dims.get("gross_tonnage", {}).get("value") if isinstance(dims.get("gross_tonnage"), dict) else 171598
        len_m = dims.get("length_overall_m", {}).get("value") if isinstance(dims.get("length_overall_m"), dict) else 315.8
        beam_m = dims.get("beam_m", {}).get("value") if isinstance(dims.get("beam_m"), dict) else 43.0
        caps = s.get("capacities", {})
        pax = caps.get("passenger_capacity_max", 5655)
        year = s.get("delivery_year", 2019)
        yard = s.get("builder", "Chantiers de l'Atlantique")

        vessel_type = "River Cruise" if "andorinha" in slug or "viking" in slug and "river" in operator.lower() else "Ocean Cruise"
        
        # Hero image mapping
        hero = "/media/msc-bellissima-hero.jpg"
        if "meraviglia" in slug:
            hero = "/media/msc-meraviglia-hero.jpg"
        elif "grandiosa" in slug:
            hero = "/media/msc-grandiosa-hero.jpg"
        elif "andorinha" in slug:
            hero = "/media/ms-andorinha-hero.jpg"

        fleet_vessels.append({
            "slug": slug,
            "name": name,
            "imo": str(imo),
            "operator": operator,
            "vesselType": vessel_type,
            "shipClass": sclass,
            "roleTitle": f"{sclass} Flagship" if "bellissima" in slug or "europa" in slug else f"{sclass} Vessel",
            "tagline": "The Digital Twin of Passenger Peace of Mind" if "bellissima" in slug else "Evidence-Backed Maritime Intelligence",
            "subtitle": f"{year} built by {yard} · {gt:,} GT".replace(",", "."),
            "heroImageUrl": hero,
            "lengthM": float(len_m),
            "beamM": float(beam_m),
            "totalDecks": 19 if gt > 150000 else 14,
            "cabinCount": int(pax / 2.5),
            "passengerCapacity": int(pax),
            "buildYear": int(year),
            "builder": yard,
            "region": "Mediterranean & Global",
            "defaultCabin": "14122" if slug == "msc-bellissima" else "10001",
            "statusLabel": "Verified Reference Twin" if slug == "msc-bellissima" else "Active Fleet Intelligence",
            "description": f"{name} is an active {vessel_type.lower()} vessel operated by {operator} and engineered by {yard}.",
            "highlights": s.get("signature_venues", ["Main Promenade", "Aurea Spa", "Grand Theatre"]),
        })

    fleet_ts_content = f"""// AUTO-GENERATED BY tools/generate_frontend_bridge.py
// DO NOT EDIT MANUALLY. SOURCE: data/cruise_intelligence_db.json

export interface FleetVessel {{
  slug: string;
  name: string;
  imo: string;
  operator: string;
  vesselType: 'Ocean Cruise' | 'River Cruise';
  shipClass: string;
  roleTitle: string;
  tagline: string;
  subtitle: string;
  heroImageUrl: string;
  lengthM: number;
  beamM: number;
  totalDecks: number;
  cabinCount: number;
  passengerCapacity: number;
  buildYear: number;
  builder: string;
  region: string;
  defaultCabin: string;
  statusLabel: string;
  description: string;
  highlights: string[];
}}

export const FLEET_REGISTRY: FleetVessel[] = {json.dumps(fleet_vessels, indent=2, ensure_ascii=False)};

export function getVesselBySlug(slug: string): FleetVessel {{
  const found = FLEET_REGISTRY.find((v) => v.slug === slug);
  return found || FLEET_REGISTRY[0];
}}
"""
    with open(os.path.join(FRONTEND_GEN_DIR, "fleet.ts"), "w", encoding="utf-8") as f:
        f.write(fleet_ts_content)
    print(f" [OK] Generated frontend/src/generated/fleet.ts with {len(fleet_vessels)} ships.")

    # 3. Generate TypeScript Port Registry
    port_records = []
    for slug, p in ports.items():
        name = p.get("name", slug.title())
        locode = p.get("un_locode", "ITGOA")
        country = p.get("country", "Italy")
        region = p.get("region", "Mediterranean")
        term = p.get("terminal_name", p.get("terminal", "Cruise Terminal"))
        coords = p.get("coordinates", {})

        port_records.append({
            "slug": slug,
            "name": name,
            "unLocode": locode,
            "country": country,
            "region": region,
            "headline": f"Strategic maritime cruise port gateway for {region}.",
            "terminalName": term,
            "berths": ["Berth 1", "Berth 2"],
            "gangwayDeckDefault": 5,
            "distanceToCenterM": 500,
            "walkingTimeMin": 10,
            "stepFreeAccess": True,
            "transitNote": "Official shuttle, public transit, or level pedestrian walkways available.",
            "airportTransit": "Regional airport connection available via express bus or taxi.",
            "currency": "Euro (€ / EUR)" if country in ["Italy", "Spain", "France", "Malta", "Germany", "Portugal"] else "USD ($)",
            "cardAcceptancePct": 98,
            "emergencyPhone": "112" if country in ["Italy", "Spain", "France", "Malta", "Germany", "Portugal"] else "911",
            "negativeIntelligence": [
                "Turn on Airplane Mode beyond port breakwaters to avoid satellite cellular roaming.",
                "Always use official port taxi stands with metered or fixed city fares."
            ],
            "officialSource": {
                "authority": f"{name} Port Authority",
                "url": "https://www.timonelo.com",
                "trustLevel": "OFFICIAL",
            },
            "callingShips": [
                {"slug": "msc-bellissima", "name": "MSC Bellissima"},
                {"slug": "msc-world-europa", "name": "MSC World Europa"},
                {"slug": "msc-meraviglia", "name": "MSC Meraviglia"}
            ],
        })

    ports_ts_content = f"""// AUTO-GENERATED BY tools/generate_frontend_bridge.py
// DO NOT EDIT MANUALLY. SOURCE: data/cruise_intelligence_db.json

export interface PortData {{
  slug: string;
  name: string;
  unLocode: string;
  country: string;
  region: string;
  headline: string;
  terminalName: string;
  berths: string[];
  gangwayDeckDefault: number;
  distanceToCenterM: number;
  walkingTimeMin: number;
  stepFreeAccess: boolean;
  transitNote: string;
  airportTransit: string;
  currency: string;
  cardAcceptancePct: number;
  emergencyPhone: string;
  negativeIntelligence: string[];
  officialSource: {{
    authority: string;
    url: string;
    trustLevel: 'OFFICIAL' | 'VERIFIED';
  }};
  callingShips: {{ slug: string; name: string }}[];
}}

export const PORTS_REGISTRY: PortData[] = {json.dumps(port_records, indent=2, ensure_ascii=False)};

export function getPortBySlug(slug: string): PortData {{
  const found = PORTS_REGISTRY.find((p) => p.slug === slug);
  return found || PORTS_REGISTRY[0];
}}
"""
    with open(os.path.join(FRONTEND_GEN_DIR, "ports.ts"), "w", encoding="utf-8") as f:
        f.write(ports_ts_content)
    print(f" [OK] Generated frontend/src/generated/ports.ts with {len(port_records)} ports.")

    # 4. Generate Precomputed Decision Cards
    decisions = [
        DecisionEngine.evaluate_ship_decision("msc-bellissima", "msc-world-europa"),
        DecisionEngine.evaluate_ship_decision("msc-bellissima", "msc-meraviglia"),
        DecisionEngine.evaluate_ship_decision("msc-bellissima", "celebrity-ascent"),
    ]
    dec_payload = [
        {
            "decisionId": d.decision_id,
            "targetEntity": d.target_entity,
            "candidateEntity": d.candidate_entity,
            "verdict": d.verdict.value,
            "warum": d.warum,
            "gruendeTop3": d.gruende_top_3,
            "unterschiede2": d.unterschiede_2,
            "risiko1": d.risiko_1,
            "naechsterSchritt": d.naechster_schritt,
            "evidenceSources": d.evidence_sources,
            "confidenceScore": d.confidence_score,
            "isDeterministic": d.is_deterministic,
        }
        for d in decisions
    ]
    dec_ts_content = f"""// AUTO-GENERATED BY tools/generate_frontend_bridge.py
// DO NOT EDIT MANUALLY. SOURCE: DecisionEngine

export interface DecisionCardData {{
  decisionId: string;
  targetEntity: string;
  candidateEntity: string;
  verdict: string;
  warum: string;
  gruendeTop3: string[];
  unterschiede2: string[];
  risiko1: string;
  naechsterSchritt: string;
  evidenceSources: string[];
  confidenceScore: number;
  isDeterministic: boolean;
}}

export const PRECOMPUTED_DECISIONS: DecisionCardData[] = {json.dumps(dec_payload, indent=2, ensure_ascii=False)};
"""
    with open(os.path.join(FRONTEND_GEN_DIR, "decisions.ts"), "w", encoding="utf-8") as f:
        f.write(dec_ts_content)
    print(f" [OK] Generated frontend/src/generated/decisions.ts with {len(dec_payload)} precomputed decision cards.")

    # 5. Generate Travel Actions & Negative Intelligence Timeline
    from src.timonelo.database.travel_intelligence import TravelIntelligenceEngine, JourneyPhase, ActionUrgency
    actions = TravelIntelligenceEngine.ACTIONS_CATALOGUE
    act_payload = [
        {
            "actionId": a.action_id,
            "phase": a.phase.value,
            "timeWindow": a.time_window,
            "urgency": a.urgency.value,
            "headline": a.headline,
            "whatToDoNow": a.what_to_do_now,
            "negativeIntelligenceToAvoid": a.negative_intelligence_to_avoid,
            "reasonsTop3": a.reasons_top_3,
            "concreteSteps": a.concrete_steps,
            "evidenceSources": a.evidence_sources,
            "confidenceScore": a.confidence_score,
            "isDeterministic": a.is_deterministic,
        }
        for a in actions
    ]
    act_ts_content = f"""// AUTO-GENERATED BY tools/generate_frontend_bridge.py
// DO NOT EDIT MANUALLY. SOURCE: TravelIntelligenceEngine

export interface TravelActionData {{
  actionId: string;
  phase: string;
  timeWindow: string;
  urgency: string;
  headline: string;
  whatToDoNow: string;
  negativeIntelligenceToAvoid: string;
  reasonsTop3: string[];
  concreteSteps: string[];
  evidenceSources: string[];
  confidenceScore: number;
  isDeterministic: boolean;
}}

export const TRAVEL_ACTIONS_REGISTRY: TravelActionData[] = {json.dumps(act_payload, indent=2, ensure_ascii=False)};
"""
    with open(os.path.join(FRONTEND_GEN_DIR, "travel_actions.ts"), "w", encoding="utf-8") as f:
        f.write(act_ts_content)
    print(f" [OK] Generated frontend/src/generated/travel_actions.ts with {len(act_payload)} travel action cards.")

    # 6. Generate Personal Journey Timelines (Shanghai -> Tokyo & Genoa Med)
    from src.timonelo.database.journey_engine import JourneyEngine
    shanghai_cfg = JourneyEngine.get_reference_shanghai_tokyo_journey()
    shanghai_cards = JourneyEngine.generate_journey_timeline(shanghai_cfg)
    med_cfg = JourneyEngine.get_reference_mediterranean_journey()
    med_cards = JourneyEngine.generate_journey_timeline(med_cfg)

    def serialize_cards(cards):
        return [
            {
                "cardId": c.card_id,
                "journeyId": c.journey_id,
                "stage": c.stage.value,
                "stageTitle": c.stage_title,
                "timeLabel": c.time_label,
                "currentObjective": c.current_objective,
                "whatToDoNow": c.what_to_do_now,
                "whatToPrepare": c.what_to_prepare,
                "negativeIntelligenceToAvoid": c.negative_intelligence_to_avoid,
                "upcomingDecision": c.upcoming_decision,
                "whyRecommendationExists": c.why_recommendation_exists,
                "evidenceSources": c.evidence_sources,
                "confidenceScore": c.confidence_score,
                "isDeterministic": c.is_deterministic,
            }
            for c in cards
        ]

    journey_ts_content = f"""// AUTO-GENERATED BY tools/generate_frontend_bridge.py
// DO NOT EDIT MANUALLY. SOURCE: JourneyEngine

export interface JourneyCardData {{
  cardId: string;
  journeyId: string;
  stage: string;
  stageTitle: string;
  timeLabel: string;
  currentObjective: string;
  whatToDoNow: string;
  whatToPrepare: string;
  negativeIntelligenceToAvoid: string;
  upcomingDecision: string;
  whyRecommendationExists: string;
  evidenceSources: string[];
  confidenceScore: number;
  isDeterministic: boolean;
}}

export interface JourneyProfile {{
  id: string;
  title: string;
  route: string;
  shipName: string;
  cabin: string;
  cards: JourneyCardData[];
}}

export const REFERENCE_JOURNEYS: JourneyProfile[] = [
  {{
    id: "bellissima-shanghai-tokyo-2026",
    title: "Shanghai nach Tokio (Transasien)",
    route: "Shanghai (Wusongkou) -> Yokohama (Tokio)",
    shipName: "MSC Bellissima",
    cabin: "14122",
    cards: {json.dumps(serialize_cards(shanghai_cards), indent=4, ensure_ascii=False)},
  }},
  {{
    id: "bellissima-genoa-med-2026",
    title: "Westliches Mittelmeer (7 Nächte Rundreise)",
    route: "Genua -> Neapel -> Messina -> Valletta -> Barcelona -> Marseille",
    shipName: "MSC Bellissima",
    cabin: "14122",
    cards: {json.dumps(serialize_cards(med_cards), indent=4, ensure_ascii=False)},
  }},
];
"""
    with open(os.path.join(FRONTEND_GEN_DIR, "journey.ts"), "w", encoding="utf-8") as f:
        f.write(journey_ts_content)
    print(f" [OK] Generated frontend/src/generated/journey.ts with 2 complete reference journey timelines.")

    # 7. Generate Destination Intelligence Guides
    from src.timonelo.database.destination_engine import DestinationIntelligenceEngine
    dests = DestinationIntelligenceEngine.list_all_destinations()
    dest_payload = [
        {
            "portSlug": d.port_slug,
            "cityName": d.city_name,
            "country": d.country,
            "primaryLanguage": d.primary_language,
            "currency": d.currency,
            "timezone": d.timezone,
            "powerPlugs": d.power_plugs.value,
            "simEsimRecommendation": d.sim_esim_recommendation,
            "emergencyPhonePolice": d.emergency_phone_police,
            "emergencyPhoneMedical": d.emergency_phone_medical,
            "localTransportCard": d.local_transport_card,
            "airports": [
                {
                    "airportName": a.airport_name,
                    "iataCode": a.iata_code,
                    "distanceToTerminalKm": a.distance_to_terminal_km,
                    "bestTransitMode": a.best_transit_mode,
                    "typicalDurationMin": a.typical_duration_min,
                    "estimatedCostRange": a.estimated_cost_range,
                    "negativeIntelligence": a.negative_intelligence,
                    "evidenceSource": a.evidence_source,
                }
                for a in d.airports
            ],
            "terminals": [
                {
                    "terminalName": t.terminal_name,
                    "berths": t.berths,
                    "porterDropoffLocation": t.porter_dropoff_location,
                    "securityLaneNotes": t.security_lane_notes,
                    "distanceToCityCenterKm": t.distance_to_city_center_km,
                    "nearestMetroOrTrain": t.nearest_metro_or_train,
                    "negativeIntelligence": t.negative_intelligence,
                }
                for t in d.terminals
            ],
            "recommendedHotelZones": d.recommended_hotel_zones,
            "negativeIntelligenceTop3": d.negative_intelligence_top_3,
            "evidenceSources": d.evidence_sources,
            "confidenceScore": d.confidence_score,
            "unknownFields": d.unknown_fields,
        }
        for d in dests
    ]

    dest_ts_content = f"""// AUTO-GENERATED BY tools/generate_frontend_bridge.py
// DO NOT EDIT MANUALLY. SOURCE: DestinationIntelligenceEngine

export interface AirportOption {{
  airportName: string;
  iataCode: string;
  distanceToTerminalKm: number;
  bestTransitMode: string;
  typicalDurationMin: number;
  estimatedCostRange: string;
  negativeIntelligence: string;
  evidenceSource: string;
}}

export interface TerminalLayout {{
  terminalName: string;
  berths: string[];
  porterDropoffLocation: string;
  securityLaneNotes: string;
  distanceToCityCenterKm: number;
  nearestMetroOrTrain: string;
  negativeIntelligence: string;
}}

export interface DestinationData {{
  portSlug: string;
  cityName: string;
  country: string;
  primaryLanguage: string;
  currency: string;
  timezone: string;
  powerPlugs: string;
  simEsimRecommendation: string;
  emergencyPhonePolice: string;
  emergencyPhoneMedical: string;
  localTransportCard: string;
  airports: AirportOption[];
  terminals: TerminalLayout[];
  recommendedHotelZones: string[];
  negativeIntelligenceTop3: string[];
  evidenceSources: string[];
  confidenceScore: number;
  unknownFields: string[];
}}

export const DESTINATIONS_REGISTRY: DestinationData[] = {json.dumps(dest_payload, indent=2, ensure_ascii=False)};

export function getDestinationBySlug(slug: string): DestinationData {{
  const found = DESTINATIONS_REGISTRY.find((d) => d.portSlug === slug);
  return found || DESTINATIONS_REGISTRY[0];
}}
"""
    with open(os.path.join(FRONTEND_GEN_DIR, "destinations.ts"), "w", encoding="utf-8") as f:
        f.write(dest_ts_content)
    print(f" [OK] Generated frontend/src/generated/destinations.ts with {len(dest_payload)} destinations.")

    # 8. Generate Personal Travel Briefings (German Senator vs US Solo)
    from src.timonelo.database.personal_intelligence import (
        PersonalIntelligenceEngine,
        TravellerProfile,
        TravelPartyType,
        MobilityLevel,
    )
    p_de = TravellerProfile(
        traveller_id="Klaus Hoffmann",
        nationality="DE",
        residence_country="Germany",
        preferred_home_airport="FRA",
        airline_loyalty="Miles & More Senator",
        hotel_loyalty="Hilton Diamond",
        cruise_loyalty="MSC Voyagers Club Gold",
        travel_party=TravelPartyType.COUPLE,
        mobility=MobilityLevel.STANDARD,
    )
    b_de = PersonalIntelligenceEngine.generate_briefing(p_de, "msc-bellissima", "MSC Bellissima", "Shanghai nach Tokio (Transasien)")

    p_us = TravellerProfile(
        traveller_id="Sarah Jenkins",
        nationality="US",
        residence_country="United States",
        preferred_home_airport="JFK",
        airline_loyalty="Delta SkyMiles Platinum",
        hotel_loyalty="Marriott Bonvoy Titanium",
        cruise_loyalty="MSC Voyagers Club Diamond",
        travel_party=TravelPartyType.FAMILY_WITH_TODDLER,
        mobility=MobilityLevel.STANDARD,
    )
    b_us = PersonalIntelligenceEngine.generate_briefing(p_us, "msc-bellissima", "MSC Bellissima", "Shanghai nach Tokio (Transasien)")

    def serialize_briefing(b):
        return {
            "briefingId": b.briefing_id,
            "travellerName": b.traveller_name,
            "nationality": b.nationality,
            "cruiseShip": b.cruise_ship,
            "cruiseRoute": b.cruise_route,
            "visaAndDocumentsStatus": [
                {
                    "destinationCountry": v.destination_country,
                    "status": v.status.value,
                    "passportValidityRequiredMonths": v.passport_validity_required_months,
                    "details": v.details,
                    "evidenceSource": v.evidence_source,
                    "confidence": v.confidence,
                }
                for v in b.visa_and_documents_status
            ],
            "loyaltyPrograms": [
                {
                    "programName": l.program_name,
                    "currentTier": l.current_tier,
                    "unlockedBenefitsOnTrip": l.unlocked_benefits_on_trip,
                    "potentialTierProgress": l.potential_tier_progress,
                    "confidenceScore": l.confidence_score,
                    "evidenceSource": l.evidence_source,
                }
                for l in b.loyalty_programs
            ],
            "importantActions": b.important_actions,
            "potentialRisks": b.potential_risks,
            "statusOpportunities": b.status_opportunities,
            "confidenceOverall": b.confidence_overall,
            "evidenceSources": b.evidence_sources,
            "isDeterministic": b.is_deterministic,
        }

    briefings_payload = [serialize_briefing(b_de), serialize_briefing(b_us)]

    personal_ts_content = f"""// AUTO-GENERATED BY tools/generate_frontend_bridge.py
// DO NOT EDIT MANUALLY. SOURCE: PersonalIntelligenceEngine

export interface VisaStatusItem {{
  destinationCountry: string;
  status: string;
  passportValidityRequiredMonths: number;
  details: string;
  evidenceSource: string;
  confidence: number;
}}

export interface LoyaltyProgramItem {{
  programName: string;
  currentTier: string;
  unlockedBenefitsOnTrip: string[];
  potentialTierProgress: string;
  confidenceScore: number;
  evidenceSource: string;
}}

export interface PersonalBriefingData {{
  briefingId: string;
  travellerName: string;
  nationality: string;
  cruiseShip: string;
  cruiseRoute: string;
  visaAndDocumentsStatus: VisaStatusItem[];
  loyaltyPrograms: LoyaltyProgramItem[];
  importantActions: string[];
  potentialRisks: string[];
  statusOpportunities: string[];
  confidenceOverall: string;
  evidenceSources: string[];
  isDeterministic: boolean;
}}

export const PRECOMPUTED_BRIEFINGS: PersonalBriefingData[] = {json.dumps(briefings_payload, indent=2, ensure_ascii=False)};
"""
    with open(os.path.join(FRONTEND_GEN_DIR, "personal_intelligence.ts"), "w", encoding="utf-8") as f:
        f.write(personal_ts_content)
    print(f" [OK] Generated frontend/src/generated/personal_intelligence.ts with {len(briefings_payload)} precomputed personal briefings.")

    # 9. Generate Global Companion 8-Phase Itinerary & Regret Score
    from src.timonelo.database.global_companion import (
        GlobalCompanionEngine,
        RegretScoreEngine,
    )
    flo_memory = GlobalCompanionEngine.get_reference_memory_flo()
    eight_phases = GlobalCompanionEngine.generate_8_phase_journey(flo_memory)
    eval_high = RegretScoreEngine.evaluate_flight_arrival_timing(True, "09:50 Uhr (04.10.)", "17:00 Uhr (04.10.)", "Shanghai")
    eval_low = RegretScoreEngine.evaluate_flight_arrival_timing(False, "Vortag (03.10.)", "17:00 Uhr (04.10.)", "Shanghai")

    phases_payload = [
        {
            "phase": p.phase.value,
            "phaseNumber": p.phase_number,
            "headline": p.headline,
            "objectiveNow": p.objective_now,
            "whatToDoNow": p.what_to_do_now,
            "negativeIntelligenceToAvoid": p.negative_intelligence_to_avoid,
            "insiderRules": p.insider_rules,
            "travelMemoryAdaptations": p.travel_memory_adaptations,
            "evidenceSources": p.evidence_sources,
            "confidenceScore": p.confidence_score,
        }
        for p in eight_phases
    ]

    memory_payload = {
        "travelerId": flo_memory.traveler_id,
        "preferredName": flo_memory.preferred_name,
        "travelStyle": flo_memory.travel_style,
        "mscLoyaltyTier": flo_memory.msc_loyalty_tier,
        "airlineTier": flo_memory.airline_tier,
        "hotelPreference": flo_memory.hotel_preference,
        "likes": flo_memory.likes,
        "dislikes": flo_memory.dislikes,
        "isSoloTraveler": flo_memory.is_solo_traveler,
        "photographyEnthusiast": flo_memory.photography_enthusiast,
        "culinaryPreference": flo_memory.culinary_preference,
    }

    regret_evals_payload = [
        {
            "scenarioTitle": eval_high.scenario_title,
            "level": eval_high.level.value,
            "regretScorePct": eval_high.regret_score_pct,
            "whyYouWillRegretThis": eval_high.why_you_will_regret_this,
            "howToAvoidRegret": eval_high.how_to_avoid_regret,
            "confidence": eval_high.confidence,
            "evidenceSource": eval_high.evidence_source,
        },
        {
            "scenarioTitle": eval_low.scenario_title,
            "level": eval_low.level.value,
            "regretScorePct": eval_low.regret_score_pct,
            "whyYouWillRegretThis": eval_low.why_you_will_regret_this,
            "howToAvoidRegret": eval_low.how_to_avoid_regret,
            "confidence": eval_low.confidence,
            "evidenceSource": eval_low.evidence_source,
        },
    ]

    companion_ts_content = f"""// AUTO-GENERATED BY tools/generate_frontend_bridge.py
// DO NOT EDIT MANUALLY. SOURCE: GlobalCompanionEngine & RegretScoreEngine

export interface TravelMemoryData {{
  travelerId: string;
  preferredName: string;
  travelStyle: string;
  mscLoyaltyTier: string;
  airlineTier: string;
  hotelPreference: string;
  likes: string[];
  dislikes: string[];
  isSoloTraveler: boolean;
  photographyEnthusiast: boolean;
  culinaryPreference: string;
}}

export interface CompanionPhaseData {{
  phase: string;
  phaseNumber: number;
  headline: string;
  objectiveNow: string;
  whatToDoNow: string[];
  negativeIntelligenceToAvoid: string;
  insiderRules: string[];
  travelMemoryAdaptations: string[];
  evidenceSources: string[];
  confidenceScore: number;
}}

export interface RegretEvaluationData {{
  scenarioTitle: string;
  level: string;
  regretScorePct: number;
  whyYouWillRegretThis: string[];
  howToAvoidRegret: string;
  confidence: number;
  evidenceSource: string;
}}

export const TRAVEL_MEMORY_FLO: TravelMemoryData = {json.dumps(memory_payload, indent=2, ensure_ascii=False)};
export const COMPANION_8_PHASES: CompanionPhaseData[] = {json.dumps(phases_payload, indent=2, ensure_ascii=False)};
export const REGRET_SCENARIOS: RegretEvaluationData[] = {json.dumps(regret_evals_payload, indent=2, ensure_ascii=False)};
"""
    with open(os.path.join(FRONTEND_GEN_DIR, "global_companion.ts"), "w", encoding="utf-8") as f:
        f.write(companion_ts_content)
    print(f" [OK] Generated frontend/src/generated/global_companion.ts with 8 phases and Regret Score engine.")

    # 10. Generate Safety Intelligence & Context Navigation
    from src.timonelo.database.safety_intelligence import (
        SafetyIntelligenceEngine,
        CurrentLocationType,
    )
    plan_cabin = SafetyIntelligenceEngine.calculate_navigation_plan("msc-bellissima", "MSC Bellissima", "14122", CurrentLocationType.CABIN)
    plan_buffet = SafetyIntelligenceEngine.calculate_navigation_plan("msc-bellissima", "MSC Bellissima", "14122", CurrentLocationType.BUFFET)
    plan_theatre = SafetyIntelligenceEngine.calculate_navigation_plan("msc-bellissima", "MSC Bellissima", "14122", CurrentLocationType.THEATRE)

    def serialize_safety_plan(p):
        return {
            "planId": p.plan_id,
            "shipName": p.ship_name,
            "cabinNumber": p.cabin_number,
            "startLocation": p.start_location,
            "assignedMusterStation": {
                "stationCode": p.assigned_muster_station.station_code,
                "deck": p.assigned_muster_station.deck,
                "side": p.assigned_muster_station.side.value,
                "venueName": p.assigned_muster_station.venue_name,
                "capacityZones": p.assigned_muster_station.capacity_zones,
                "primaryLifeboatNumbers": p.assigned_muster_station.primary_lifeboat_numbers,
                "evidenceSource": p.assigned_muster_station.evidence_source,
            },
            "distanceMeters": p.distance_meters,
            "estimatedWalkingTimeMin": p.estimated_walking_time_min,
            "deckChanges": p.deck_changes,
            "primaryRouteSteps": [
                {
                    "stepNumber": s.step_number,
                    "instruction": s.instruction,
                    "deck": s.deck,
                    "transitElement": s.transit_element,
                    "orientationHint": s.orientation_hint,
                }
                for s in p.primary_route_steps
            ],
            "alternativeRouteSteps": [
                {
                    "stepNumber": s.step_number,
                    "instruction": s.instruction,
                    "deck": s.deck,
                    "transitElement": s.transit_element,
                    "orientationHint": s.orientation_hint,
                }
                for s in p.alternative_route_steps
            ],
            "negativeIntelligenceRules": p.negative_intelligence_rules,
            "safetyDrillStatus": p.safety_drill_status,
            "isDeterministic": p.is_deterministic,
            "confidenceScore": p.confidence_score,
        }

    safety_payload = {
        "cabin": serialize_safety_plan(plan_cabin),
        "buffet": serialize_safety_plan(plan_buffet),
        "theatre": serialize_safety_plan(plan_theatre),
    }

    safety_ts_content = f"""// AUTO-GENERATED BY tools/generate_frontend_bridge.py
// DO NOT EDIT MANUALLY. SOURCE: SafetyIntelligenceEngine

export interface MusterStationData {{
  stationCode: string;
  deck: number;
  side: string;
  venueName: string;
  capacityZones: string;
  primaryLifeboatNumbers: number[];
  evidenceSource: string;
}}

export interface SafetyStepData {{
  stepNumber: number;
  instruction: string;
  deck: number;
  transitElement: string;
  orientationHint: string;
}}

export interface SafetyPlanData {{
  planId: string;
  shipName: string;
  cabinNumber: string;
  startLocation: string;
  assignedMusterStation: MusterStationData;
  distanceMeters: number;
  estimatedWalkingTimeMin: number;
  deckChanges: number;
  primaryRouteSteps: SafetyStepData[];
  alternativeRouteSteps: SafetyStepData[];
  negativeIntelligenceRules: string[];
  safetyDrillStatus: string;
  isDeterministic: boolean;
  confidenceScore: number;
}}

export const PRECOMPUTED_SAFETY_PLANS: Record<string, SafetyPlanData> = {json.dumps(safety_payload, indent=2, ensure_ascii=False)};
"""
    with open(os.path.join(FRONTEND_GEN_DIR, "safety_intelligence.ts"), "w", encoding="utf-8") as f:
        f.write(safety_ts_content)
    print(f" [OK] Generated frontend/src/generated/safety_intelligence.ts with 3 context navigation safety plans.")

    # 11. Generate Bridge Officer Tim (BOT) Daily Briefings
    from src.timonelo.database.bridge_officer import (
        BridgeOfficerEngine,
        BriefingPhase,
    )
    briefing_pre12 = BridgeOfficerEngine.generate_briefing(BriefingPhase.PRE_CRUISE_12D, "Florian", "MSC Bellissima", "14122")
    briefing_embark = BridgeOfficerEngine.generate_briefing(BriefingPhase.EMBARKATION_BOARDING, "Florian", "MSC Bellissima", "14122")
    briefing_sea = BridgeOfficerEngine.generate_briefing(BriefingPhase.SEA_DAY, "Florian", "MSC Bellissima", "14122")
    briefing_yokohama = BridgeOfficerEngine.generate_briefing(BriefingPhase.PORT_YOKOHAMA, "Florian", "MSC Bellissima", "14122")

    def serialize_briefing_bot(b):
        return {
            "briefingId": b.briefing_id,
            "dateDisplay": b.date_display,
            "greetingLine": b.greeting_line,
            "phaseContext": b.phase_context,
            "proactiveNotices": [
                {
                    "noticeId": n.notice_id,
                    "headline": n.headline,
                    "content": n.content,
                    "urgency": n.urgency,
                    "evidenceSource": n.evidence_source,
                }
                for n in b.proactive_notices
            ],
            "dailyFocusPoints": b.daily_focus_points,
            "maritimeInsight": b.maritime_insight,
            "signOff": b.sign_off,
            "confidenceScore": b.confidence_score,
            "isDeterministic": b.is_deterministic,
        }

    bot_payload = {
        "pre12": serialize_briefing_bot(briefing_pre12),
        "embarkation": serialize_briefing_bot(briefing_embark),
        "seaday": serialize_briefing_bot(briefing_sea),
        "yokohama": serialize_briefing_bot(briefing_yokohama),
    }

    bot_ts_content = f"""// AUTO-GENERATED BY tools/generate_frontend_bridge.py
// DO NOT EDIT MANUALLY. SOURCE: BridgeOfficerEngine (BOT v1.0)

export interface ProactiveNoticeData {{
  noticeId: string;
  headline: string;
  content: string;
  urgency: string;
  evidenceSource: string;
}}

export interface BridgeBriefingData {{
  briefingId: string;
  dateDisplay: string;
  greetingLine: string;
  phaseContext: string;
  proactiveNotices: ProactiveNoticeData[];
  dailyFocusPoints: string[];
  maritimeInsight: string;
  signOff: string;
  confidenceScore: number;
  isDeterministic: boolean;
}}

export const PRECOMPUTED_BOT_BRIEFINGS: Record<string, BridgeBriefingData> = {json.dumps(bot_payload, indent=2, ensure_ascii=False)};
"""
    with open(os.path.join(FRONTEND_GEN_DIR, "bridge_briefing.ts"), "w", encoding="utf-8") as f:
        f.write(bot_ts_content)
    print(f" [OK] Generated frontend/src/generated/bridge_briefing.ts with 4 Bridge Officer Tim daily briefings.")

    # 12. Generate Complete Travel Preparation Intelligence (Flight, Hotel, Status, Visa, Transfer)
    from src.timonelo.database.flight_intelligence import (
        FlightIntelligenceEngine,
        FlightSegment,
        AirlineAlliance,
    )
    from src.timonelo.database.hotel_intelligence import HotelIntelligenceEngine
    from src.timonelo.database.status_programs import StatusProgramsEngine
    from src.timonelo.database.personal_intelligence import TravelRulesEngine

    flt_segments = [
        FlightSegment("LH728", "FRA", "PVG", "17:15", "11:40 (+1)", "Lufthansa", AirlineAlliance.STAR_ALLIANCE)
    ]
    flt_eval = FlightIntelligenceEngine.evaluate_itinerary(flt_segments, "2026-10-15", "Miles & More Senator")
    pvg_hub = FlightIntelligenceEngine.AIRPORT_REGISTRY["PVG"]
    hyatt_hotel = HotelIntelligenceEngine.get_hotel_by_id("hyatt-on-the-bund-shanghai")
    msc_stat = StatusProgramsEngine.evaluate_status("MSC Voyagers Club", "Diamond")
    hyatt_stat = StatusProgramsEngine.evaluate_status("World of Hyatt", "Globalist")
    visa_rules = TravelRulesEngine.evaluate_rules("DE", ["China", "Japan"])

    prep_payload = {
        "flight": {
            "flightNumber": flt_segments[0].flight_number,
            "carrierName": flt_segments[0].carrier_name,
            "route": f"{flt_segments[0].departure_airport_iata} -> {flt_segments[0].arrival_airport_iata}",
            "departureTime": flt_segments[0].departure_time_local,
            "arrivalTime": flt_segments[0].arrival_time_local,
            "loungeSummary": flt_eval.lounge_eligibility_summary,
            "connectionRisk": flt_eval.connection_risk.value,
            "botRecommendation": flt_eval.bot_recommendation,
            "negativeIntelligence": flt_eval.negative_intelligence,
            "airportHub": {
                "iataCode": pvg_hub.iata_code,
                "name": pvg_hub.airport_name,
                "immigrationTime": f"~{pvg_hub.immigration_duration_est_min} min",
                "publicTransit": pvg_hub.public_transport_connection,
                "taxiAdvice": pvg_hub.taxi_advice_and_scams,
            },
        },
        "hotel": {
            "propertyName": hyatt_hotel.property_name if hyatt_hotel else "Hyatt on the Bund",
            "city": hyatt_hotel.city if hyatt_hotel else "Shanghai",
            "chainLoyalty": hyatt_hotel.chain_loyalty_program if hyatt_hotel else "World of Hyatt",
            "distanceToTerminal": f"{hyatt_hotel.distance_to_terminal_km} km" if hyatt_hotel else "23.5 km",
            "transferDuration": f"~{hyatt_hotel.typical_transfer_duration_min} min" if hyatt_hotel else "50 min",
            "departureRecommendation": hyatt_hotel.recommended_departure_time if hyatt_hotel else "10:45 Uhr",
            "breakfastTime": hyatt_hotel.breakfast_start_time if hyatt_hotel else "06:30 Uhr",
            "lateCheckout": hyatt_hotel.late_checkout_possibility if hyatt_hotel else "Bis 14:00 Uhr",
            "conveniences": hyatt_hotel.nearby_conveniences if hyatt_hotel else [],
            "botVerdict": hyatt_hotel.bot_evaluation_verdict if hyatt_hotel else "",
            "negativeIntelligence": hyatt_hotel.negative_intelligence if hyatt_hotel else "",
        },
        "loyalty": [
            {
                "programName": msc_stat.program_name,
                "tierName": msc_stat.tier_name,
                "keyPerks": msc_stat.key_unlocked_perks,
                "lateCheckout": msc_stat.guaranteed_late_checkout,
                "pointsEstimate": msc_stat.cruise_points_estimate,
            },
            {
                "programName": hyatt_stat.program_name,
                "tierName": hyatt_stat.tier_name,
                "keyPerks": hyatt_stat.key_unlocked_perks,
                "lateCheckout": hyatt_stat.guaranteed_late_checkout,
                "pointsEstimate": hyatt_stat.cruise_points_estimate,
            },
        ],
        "visaRequirements": [
            {
                "country": v.destination_country,
                "status": v.status.value,
                "passportValidity": f"Mindestens {v.passport_validity_required_months} Monate",
                "details": v.details,
            }
            for v in visa_rules
        ],
        "transfer": {
            "pickupLocation": "Hyatt on the Bund",
            "destination": "Wusongkou Cruise Terminal Gate 2",
            "bestOption": "Didi Taxi via Alipay (Pauschalpreis ~¥120–¥160)",
            "departureTime": "10:45 Uhr",
            "terminalArrival": "11:35 Uhr",
            "negativeIntelligence": "Niemals inoffizielle Taxis vor dem Hotel oder Terminal annehmen; Festpreise über Alipay sind bindend.",
        },
    }

    prep_ts_content = f"""// AUTO-GENERATED BY tools/generate_frontend_bridge.py
// DO NOT EDIT MANUALLY. SOURCE: Flight, Hotel, Status, and Visa Engines

export interface AirportHubData {{
  iataCode: string;
  name: string;
  immigrationTime: string;
  publicTransit: string;
  taxiAdvice: string;
}}

export interface FlightPreparationData {{
  flightNumber: string;
  carrierName: string;
  route: string;
  departureTime: string;
  arrivalTime: string;
  loungeSummary: string;
  connectionRisk: string;
  botRecommendation: string;
  negativeIntelligence: string;
  airportHub: AirportHubData;
}}

export interface HotelPreparationData {{
  propertyName: string;
  city: string;
  chainLoyalty: string;
  distanceToTerminal: string;
  transferDuration: string;
  departureRecommendation: string;
  breakfastTime: string;
  lateCheckout: string;
  conveniences: string[];
  botVerdict: string;
  negativeIntelligence: string;
}}

export interface LoyaltyPerkData {{
  programName: string;
  tierName: string;
  keyPerks: string[];
  lateCheckout: string;
  pointsEstimate: string;
}}

export interface VisaPrepData {{
  country: string;
  status: string;
  passportValidity: string;
  details: string;
}}

export interface TransferPrepData {{
  pickupLocation: string;
  destination: string;
  bestOption: string;
  departureTime: string;
  terminalArrival: string;
  negativeIntelligence: string;
}}

export interface TravelPreparationDashboardData {{
  flight: FlightPreparationData;
  hotel: HotelPreparationData;
  loyalty: LoyaltyPerkData[];
  visaRequirements: VisaPrepData[];
  transfer: TransferPrepData;
}}

export const TRAVEL_PREPARATION_DATA: TravelPreparationDashboardData = {json.dumps(prep_payload, indent=2, ensure_ascii=False)};
"""
    with open(os.path.join(FRONTEND_GEN_DIR, "travel_preparation.ts"), "w", encoding="utf-8") as f:
        f.write(prep_ts_content)
    print(f" [OK] Generated frontend/src/generated/travel_preparation.ts for complete pre-cruise dashboard.")

    # 13. Generate Port & City Intelligence Profiles
    from src.timonelo.database.port_city_intelligence import PortCityIntelligenceEngine
    cities = PortCityIntelligenceEngine.list_all_destinations()
    cities_payload = [
        {
            "citySlug": c.city_slug,
            "officialName": c.official_name,
            "country": c.country,
            "timezone": c.timezone,
            "currency": c.currency,
            "language": c.language,
            "emergencyPolice": c.emergency_police,
            "emergencyMedical": c.emergency_medical,
            "plugType": c.plug_type,
            "tapWater": c.tap_water.value,
            "cardVsCashCulture": c.card_vs_cash_culture,
            "simEsimAdvice": c.sim_esim_advice,
            "rideHailingApps": c.ride_hailing_apps,
            "publicTransportSummary": c.public_transport_summary,
            "walkingFriendliness": c.walking_friendliness,
            "accessibilityNotes": c.accessibility_notes,
            "weatherProfileSummary": c.weather_profile_summary,
            "terminalName": c.terminal_name,
            "gangwaySteps": [
                {
                    "stepNum": s.step_num,
                    "title": s.title,
                    "instruction": s.instruction,
                    "typicalMinutes": s.typical_minutes,
                    "orientationHint": s.orientation_hint,
                }
                for s in c.gangway_steps
            ],
            "shoreTime": {
                "scheduledArrival": c.shore_time.scheduled_arrival,
                "scheduledAllAboard": c.shore_time.scheduled_all_aboard,
                "recommendedLatestReturn": c.shore_time.recommended_latest_return,
                "safeBufferMinutes": c.shore_time.safe_buffer_minutes,
                "rushHourWarningWindow": c.shore_time.rush_hour_warning_window,
                "safeWalkingRadiusKm": c.shore_time.safe_walking_radius_km,
            },
            "negativeIntelligenceTraps": c.negative_intelligence_traps,
            "localCulinaryTips": c.local_culinary_tips,
            "botProactiveNotices": c.bot_proactive_notices,
            "botClosingPhrase": c.bot_closing_phrase,
            "evidenceSources": c.evidence_sources,
            "confidenceScore": c.confidence_score,
        }
        for c in cities
    ]

    port_city_ts_content = f"""// AUTO-GENERATED BY tools/generate_frontend_bridge.py
// DO NOT EDIT MANUALLY. SOURCE: PortCityIntelligenceEngine

export interface GangwayStepData {{
  stepNum: number;
  title: string;
  instruction: string;
  typicalMinutes: number;
  orientationHint: string;
}}

export interface ShoreTimeData {{
  scheduledArrival: string;
  scheduledAllAboard: string;
  recommendedLatestReturn: string;
  safeBufferMinutes: number;
  rushHourWarningWindow: string;
  safeWalkingRadiusKm: number;
}}

export interface PortCityProfileData {{
  citySlug: string;
  officialName: string;
  country: string;
  timezone: string;
  currency: string;
  language: string;
  emergencyPolice: string;
  emergencyMedical: string;
  plugType: string;
  tapWater: string;
  cardVsCashCulture: string;
  simEsimAdvice: string;
  rideHailingApps: string[];
  publicTransportSummary: string;
  walkingFriendliness: string;
  accessibilityNotes: string;
  weatherProfileSummary: string;
  terminalName: string;
  gangwaySteps: GangwayStepData[];
  shoreTime: ShoreTimeData;
  negativeIntelligenceTraps: string[];
  localCulinaryTips: string[];
  botProactiveNotices: string[];
  botClosingPhrase: string;
  evidenceSources: string[];
  confidenceScore: number;
}}

export const PORT_CITY_PROFILES: PortCityProfileData[] = {json.dumps(cities_payload, indent=2, ensure_ascii=False)};

export function getPortCityProfileBySlug(slug: string): PortCityProfileData {{
  const found = PORT_CITY_PROFILES.find((c) => c.citySlug === slug);
  return found || PORT_CITY_PROFILES[0];
}}
"""
    with open(os.path.join(FRONTEND_GEN_DIR, "port_city_intelligence.ts"), "w", encoding="utf-8") as f:
        f.write(port_city_ts_content)
    print(f" [OK] Generated frontend/src/generated/port_city_intelligence.ts with {len(cities_payload)} canonical port cities.")

    # 14. Generate Context Engine & Proactive Bridge Briefings
    from src.timonelo.database.context_engine import (
        ContextEngine,
        TravellerContext,
        JourneyContext,
        BotMemory,
        CurrentPhase,
    )

    briefing_pre12 = ContextEngine.generate_context_briefing(simulated_date_iso="2026-10-03")
    briefing_t3 = ContextEngine.generate_context_briefing(simulated_date_iso="2026-10-12")
    briefing_boarding = ContextEngine.generate_context_briefing(simulated_date_iso="2026-10-15")

    context_payload = {
        "pre12": {
            "briefingId": briefing_pre12.briefing_id,
            "phase": briefing_pre12.phase.value,
            "dateDisplay": briefing_pre12.date_display,
            "greetingLine": briefing_pre12.greeting_line,
            "statusHeadline": briefing_pre12.status_headline,
            "proactiveBotNotices": briefing_pre12.proactive_bot_notices,
            "topPriorities": [
                {
                    "taskId": t.task_id,
                    "title": t.title,
                    "priority": t.priority.value,
                    "deadlineDisplay": t.deadline_display,
                    "daysRemaining": t.days_remaining,
                    "evidenceSource": t.evidence_source,
                    "reason": t.reason,
                    "recommendedAction": t.recommended_action,
                }
                for t in briefing_pre12.top_priorities
            ],
            "completedMilestones": briefing_pre12.completed_milestones,
            "signOffPhrase": briefing_pre12.sign_off_phrase,
        },
        "t3": {
            "briefingId": briefing_t3.briefing_id,
            "phase": briefing_t3.phase.value,
            "dateDisplay": "Montag, 12. Oktober 2026 · T-3 Tage (Check-in offen)",
            "greetingLine": "Guten Morgen, Florian.",
            "statusHeadline": "Der Web-Check-in für MSC Bellissima ist jetzt freigeschaltet. Kofferanhänger bereit.",
            "proactiveBotNotices": [
                "BOT noticed: Online-Check-in ist ab sofort im MSC Portal verfügbar.",
                "BOT noticed: Drucken Sie die Kofferanhänger für Kabine 14122 in Farbe oder Schwarzweiß aus.",
            ],
            "topPriorities": [
                {
                    "taskId": "task:checkin-now",
                    "title": "MSC Web-Check-in abschließen & Kofferanhänger drucken",
                    "priority": "HIGH",
                    "deadlineDisplay": "Heute",
                    "daysRemaining": 3,
                    "evidenceSource": "src:msc-operations",
                    "reason": "Vollständiger Check-in sichert das gebuchte 11:30 Uhr Einschiffungszeitfenster.",
                    "recommendedAction": "Bordkarte & Baggage Tags digital in Apple Wallet sichern.",
                }
            ],
            "completedMilestones": [
                "Reisepass & 15-Tage-Visumfreiheit verifiziert",
                "Alipay & Didi mit Kreditkarte verknüpft",
            ],
            "signOffPhrase": "I have reviewed your journey. Everything is proceeding as expected. I remain on the bridge.",
        },
    }

    context_ts_content = f"""// AUTO-GENERATED BY tools/generate_frontend_bridge.py
// DO NOT EDIT MANUALLY. SOURCE: ContextEngine

export interface OutstandingTaskData {{
  taskId: string;
  title: string;
  priority: string;
  deadlineDisplay: string;
  daysRemaining: number;
  evidenceSource: string;
  reason: string;
  recommendedAction: string;
}}

export interface ContextBriefingData {{
  briefingId: string;
  phase: string;
  dateDisplay: string;
  greetingLine: string;
  statusHeadline: string;
  proactiveBotNotices: string[];
  topPriorities: OutstandingTaskData[];
  completedMilestones: string[];
  signOffPhrase: string;
}}

export const CONTEXT_BRIEFINGS: Record<string, ContextBriefingData> = {json.dumps(context_payload, indent=2, ensure_ascii=False)};
"""
    with open(os.path.join(FRONTEND_GEN_DIR, "context_engine.ts"), "w", encoding="utf-8") as f:
        f.write(context_ts_content)
    print(f" [OK] Generated frontend/src/generated/context_engine.ts for Context Briefing Dashboard.")

    # 15. Generate Cruise Assistant & Concierge Engine
    from src.timonelo.database.assistant_engine import (
        AssistantEngine,
        QuickActionQuery,
        SuggestionCategory,
    )

    daily_mission = AssistantEngine.get_daily_mission("morning_yokohama")
    free_time_bundle = AssistantEngine.evaluate_free_time(hours_available=2.0)
    quick_lunch = AssistantEngine.answer_quick_action(QuickActionQuery.LUNCH_WHERE)
    quick_sunset = AssistantEngine.answer_quick_action(QuickActionQuery.SUNSET_SPOT)
    quick_coffee = AssistantEngine.answer_quick_action(QuickActionQuery.QUIET_COFFEE)
    quick_muster = AssistantEngine.answer_quick_action(QuickActionQuery.MUSTER_STATION)

    assistant_payload = {
        "dailyMission": {
            "missionId": daily_mission.mission_id,
            "phaseName": daily_mission.phase_name,
            "missionTitle": daily_mission.mission_title,
            "currentObjective": daily_mission.current_objective,
            "recommendedActions": daily_mission.recommended_actions,
            "negativeIntelligenceAvoid": daily_mission.negative_intelligence_avoid,
            "estimatedDurationDisplay": daily_mission.estimated_duration_display,
            "evidenceSource": daily_mission.evidence_source,
        },
        "freeTimeBundle": {
            "queryText": free_time_bundle.query_text,
            "botOpeningLine": free_time_bundle.bot_opening_line,
            "recommendedOptions": [
                {
                    "optionId": opt.option_id,
                    "title": opt.title,
                    "deckLocation": opt.deck_location,
                    "category": opt.category.value,
                    "timeRequiredMin": opt.time_required_min,
                    "walkingEffort": opt.walking_effort,
                    "crowdLevel": opt.crowd_level,
                    "isAccessible": opt.is_accessible,
                    "isRestricted": opt.is_restricted,
                    "restrictionNote": opt.restriction_note,
                    "reasoning": opt.reasoning,
                    "evidenceSource": opt.evidence_source,
                }
                for opt in free_time_bundle.recommended_options
            ],
            "topRecommendationId": free_time_bundle.top_recommendation_id,
            "botConclusionLine": free_time_bundle.bot_conclusion_line,
        },
        "quickActions": {
            "lunch": {
                "title": "Mittagessen",
                "opening": quick_lunch.bot_opening_line,
                "venues": [
                    {
                        "name": opt.title,
                        "deck": opt.deck_location,
                        "desc": opt.reasoning,
                        "time": f"~{opt.time_required_min} min",
                    }
                    for opt in quick_lunch.recommended_options
                ],
                "conclusion": quick_lunch.bot_conclusion_line,
            },
            "sunset": {
                "title": "Sonnenuntergang",
                "opening": quick_sunset.bot_opening_line,
                "venues": [
                    {
                        "name": opt.title,
                        "deck": opt.deck_location,
                        "desc": opt.reasoning,
                        "time": f"~{opt.time_required_min} min",
                    }
                    for opt in quick_sunset.recommended_options
                ],
                "conclusion": quick_sunset.bot_conclusion_line,
            },
            "coffee": {
                "title": "Ruhiger Espresso",
                "opening": quick_coffee.bot_opening_line,
                "venues": [
                    {
                        "name": opt.title,
                        "deck": opt.deck_location,
                        "desc": opt.reasoning,
                        "time": f"~{opt.time_required_min} min",
                    }
                    for opt in quick_coffee.recommended_options
                ],
                "conclusion": quick_coffee.bot_conclusion_line,
            },
            "muster": {
                "title": "Musterstation",
                "opening": quick_muster.bot_opening_line,
                "venues": [
                    {
                        "name": opt.title,
                        "deck": opt.deck_location,
                        "desc": opt.reasoning,
                        "time": f"~{opt.time_required_min} min",
                    }
                    for opt in quick_muster.recommended_options
                ],
                "conclusion": quick_muster.bot_conclusion_line,
            },
        },
    }

    assistant_ts_content = f"""// AUTO-GENERATED BY tools/generate_frontend_bridge.py
// DO NOT EDIT MANUALLY. SOURCE: AssistantEngine

export interface DecisionOptionData {{
  optionId: string;
  title: string;
  deckLocation: string;
  category: string;
  timeRequiredMin: number;
  walkingEffort: string;
  crowdLevel: string;
  isAccessible: boolean;
  isRestricted: boolean;
  restrictionNote: string | null;
  reasoning: string;
  evidenceSource: string;
}}

export interface DailyMissionData {{
  missionId: string;
  phaseName: string;
  missionTitle: string;
  currentObjective: string;
  recommendedActions: string[];
  negativeIntelligenceAvoid: string[];
  estimatedDurationDisplay: string;
  evidenceSource: string;
}}

export interface QuickActionData {{
  title: string;
  opening: string;
  venues: Array<{{
    name: string;
    deck: string;
    desc: string;
    time: string;
  }}>;
  conclusion: string;
}}

export interface CruiseAssistantDashboardData {{
  dailyMission: DailyMissionData;
  freeTimeBundle: {{
    queryText: string;
    botOpeningLine: string;
    recommendedOptions: DecisionOptionData[];
    topRecommendationId: string;
    botConclusionLine: string;
  }};
  quickActions: Record<string, QuickActionData>;
}}

export const CRUISE_ASSISTANT_DATA: CruiseAssistantDashboardData = {json.dumps(assistant_payload, indent=2, ensure_ascii=False)};
"""
    with open(os.path.join(FRONTEND_GEN_DIR, "assistant_engine.ts"), "w", encoding="utf-8") as f:
        f.write(assistant_ts_content)
    print(f" [OK] Generated frontend/src/generated/assistant_engine.ts for Cruise Assistant Dashboard.")

    # 16. Generate First Voyage Simulation & Product Audit Engine
    from src.timonelo.database.first_voyage_engine import (
        FirstVoyageEngine,
        JourneyStage,
        ProductAuditEngine,
    )

    readiness = FirstVoyageEngine.calculate_journey_readiness(flight_confirmed=False)
    prep_stage = FirstVoyageEngine.get_stage_detail(JourneyStage.PREPARATION)
    embark_stage = FirstVoyageEngine.get_stage_detail(JourneyStage.EMBARKATION)
    home_stage = FirstVoyageEngine.get_stage_detail(JourneyStage.HOME)
    anti_regrets = FirstVoyageEngine.get_anti_regret_register()
    audit_rep = ProductAuditEngine.evaluate_experience()

    first_voyage_payload = {
        "readiness": {
            "totalScore": readiness.total_score,
            "isReadyForDeparture": readiness.is_ready_for_departure,
            "statusLabel": readiness.status_label,
            "verifiedItems": readiness.verified_items,
            "deductions": [
                {
                    "itemName": d.item_name,
                    "pointsDeducted": d.points_deducted,
                    "reason": d.reason,
                    "actionToResolve": d.action_to_resolve,
                    "evidenceSource": d.evidence_source,
                }
                for d in readiness.deductions
            ],
            "botVerdict": readiness.bot_verdict,
        },
        "stages": {
            "preparation": {
                "title": prep_stage.title,
                "objective": prep_stage.objective,
                "botBriefing": prep_stage.bot_morning_briefing,
                "completed": prep_stage.completed_milestones,
                "outstanding": prep_stage.outstanding_actions,
                "antiRegret": prep_stage.anti_regret_warning,
                "duration": prep_stage.estimated_duration,
            },
            "embarkation": {
                "title": embark_stage.title,
                "objective": embark_stage.objective,
                "botBriefing": embark_stage.bot_morning_briefing,
                "completed": embark_stage.completed_milestones,
                "outstanding": embark_stage.outstanding_actions,
                "antiRegret": embark_stage.anti_regret_warning,
                "duration": embark_stage.estimated_duration,
            },
            "home": {
                "title": home_stage.title,
                "objective": home_stage.objective,
                "botBriefing": home_stage.bot_morning_briefing,
                "completed": home_stage.completed_milestones,
                "outstanding": home_stage.outstanding_actions,
                "antiRegret": home_stage.anti_regret_warning,
                "duration": home_stage.estimated_duration,
            },
        },
        "antiRegrets": [
            {
                "stageName": r.stage_name,
                "trap": r.typical_regret_trap,
                "prevention": r.prevention_rule,
                "evidence": r.evidence_source,
            }
            for r in anti_regrets
        ],
        "audit": {
            "totalUxScore": audit_rep.total_ux_score,
            "clarityVerdict": audit_rep.clarity_verdict,
            "duplicateInfoDetected": audit_rep.duplicate_info_detected,
            "unnecessaryClicksCount": audit_rep.unnecessary_clicks_count,
            "unnecessaryQuestionsAsked": audit_rep.unnecessary_questions_asked,
            "proactiveTimingScore": audit_rep.proactive_timing_score,
            "summary": audit_rep.audit_summary,
        },
        "finalFarewell": "Welcome home, Florian. I hope your voyage was everything you had hoped for. Whenever you're ready for your next adventure, I'll be here on the bridge.",
    }

    first_voyage_ts_content = f"""// AUTO-GENERATED BY tools/generate_frontend_bridge.py
// DO NOT EDIT MANUALLY. SOURCE: FirstVoyageEngine & ProductAuditEngine

export interface ReadinessDeductionData {{
  itemName: string;
  pointsDeducted: number;
  reason: string;
  actionToResolve: string;
  evidenceSource: string;
}}

export interface JourneyReadinessData {{
  totalScore: number;
  isReadyForDeparture: boolean;
  statusLabel: string;
  verifiedItems: string[];
  deductions: ReadinessDeductionData[];
  botVerdict: string;
}}

export interface StageTimelineDetailData {{
  title: string;
  objective: string;
  botBriefing: string;
  completed: string[];
  outstanding: string[];
  antiRegret: string;
  duration: string;
}}

export interface AntiRegretItemData {{
  stageName: string;
  trap: string;
  prevention: string;
  evidence: string;
}}

export interface ProductAuditData {{
  totalUxScore: number;
  clarityVerdict: string;
  duplicateInfoDetected: boolean;
  unnecessaryClicksCount: number;
  unnecessaryQuestionsAsked: number;
  proactiveTimingScore: number;
  summary: string;
}}

export interface FirstVoyageDashboardData {{
  readiness: JourneyReadinessData;
  stages: Record<string, StageTimelineDetailData>;
  antiRegrets: AntiRegretItemData[];
  audit: ProductAuditData;
  finalFarewell: string;
}}

export const FIRST_VOYAGE_DATA: FirstVoyageDashboardData = {json.dumps(first_voyage_payload, indent=2, ensure_ascii=False)};
"""
    with open(os.path.join(FRONTEND_GEN_DIR, "first_voyage.ts"), "w", encoding="utf-8") as f:
        f.write(first_voyage_ts_content)
    print(f" [OK] Generated frontend/src/generated/first_voyage.ts for First Voyage Simulation.")

    # 17. Generate Experience & Voyage Culture Intelligence
    from src.timonelo.database.experience_intelligence import (
        ExperienceIntelligenceEngine,
        ExperienceType,
        DressCode,
    )

    profiles = ExperienceIntelligenceEngine.list_all_experience_profiles()
    exp_payload = [
        {
            "voyageId": p.voyage_id,
            "shipName": p.ship_name,
            "experienceType": p.experience_type.value,
            "charterOrganizer": p.charter_organizer,
            "voyageThemeTitle": p.voyage_theme_title,
            "description": p.description,
            "communityHighlights": p.community_highlights,
            "dressGuidanceSummary": p.dress_guidance_summary,
            "eventsSchedule": [
                {
                    "eventId": ev.event_id,
                    "title": ev.title,
                    "startTime": ev.start_time,
                    "venueName": ev.venue_name,
                    "deckLocation": ev.deck_location,
                    "dressCode": ev.dress_code.value,
                    "crowdExpectation": ev.crowd_expectation,
                    "description": ev.description,
                    "isOptional": ev.is_optional,
                    "quieterAlternativeVenue": ev.quieter_alternative_venue,
                }
                for ev in p.events_schedule
            ],
            "busyAreasToAvoid": p.busy_areas_to_avoid,
            "quietRetreatVenues": p.quiet_retreat_venues,
            "botProactiveObservations": p.bot_proactive_observations,
            "botEveningSignOff": p.bot_evening_sign_off,
            "evidenceSource": p.evidence_source,
            "confidenceScore": p.confidence_score,
        }
        for p in profiles
    ]

    exp_ts_content = f"""// AUTO-GENERATED BY tools/generate_frontend_bridge.py
// DO NOT EDIT MANUALLY. SOURCE: ExperienceIntelligenceEngine

export interface VoyageEventData {{
  eventId: string;
  title: string;
  startTime: string;
  venueName: string;
  deckLocation: string;
  dressCode: string;
  crowdExpectation: string;
  description: string;
  isOptional: boolean;
  quieterAlternativeVenue: string | null;
}}

export interface ExperienceProfileData {{
  voyageId: string;
  shipName: string;
  experienceType: string;
  charterOrganizer: string | null;
  voyageThemeTitle: string;
  description: string;
  communityHighlights: string[];
  dressGuidanceSummary: string;
  eventsSchedule: VoyageEventData[];
  busyAreasToAvoid: string[];
  quietRetreatVenues: string[];
  botProactiveObservations: string[];
  botEveningSignOff: string;
  evidenceSource: string;
  confidenceScore: number;
}}

export const EXPERIENCE_PROFILES: ExperienceProfileData[] = {json.dumps(exp_payload, indent=2, ensure_ascii=False)};

export function getExperienceProfileById(id: string): ExperienceProfileData {{
  const found = EXPERIENCE_PROFILES.find((p) => p.voyageId === id);
  return found || EXPERIENCE_PROFILES[0];
}}
"""
    with open(os.path.join(FRONTEND_GEN_DIR, "experience_intelligence.ts"), "w", encoding="utf-8") as f:
        f.write(exp_ts_content)
    print(f" [OK] Generated frontend/src/generated/experience_intelligence.ts with {len(exp_payload)} experience profiles.")

    # 18. Generate Shipmate Memory & Bridge Logbook
    from src.timonelo.database.shipmate_memory import (
        BridgeMemoryEngine,
        HabitCategory,
    )

    profile = BridgeMemoryEngine.get_shipmate_profile("Florian")
    memory_insights = BridgeMemoryEngine.generate_proactive_memory_insights("Florian")

    shipmate_payload = {
        "travellerName": profile.traveller_name,
        "totalVoyagesCount": profile.total_voyages_count,
        "totalSeaDays": profile.total_sea_days,
        "visitedCountries": profile.visited_countries,
        "visitedPorts": profile.visited_ports,
        "visitedShips": profile.visited_ships,
        "favouritePlaces": [
            {
                "locationId": f.location_id,
                "name": f.name,
                "category": f.category,
                "shipName": f.ship_name,
                "deckLocation": f.deck_location,
                "whyFavoured": f.why_favoured,
            }
            for f in profile.favourite_places
        ],
        "confirmedHabits": [
            {
                "habitId": h.habit_id,
                "category": h.category.value,
                "observation": h.observation,
                "evidenceVoyage": h.evidence_voyage,
            }
            for h in profile.confirmed_habits
        ],
        "voyageHistory": [
            {
                "voyageId": v.voyage_id,
                "shipName": v.ship_name,
                "cruiseLine": v.cruise_line,
                "departureDate": v.departure_date,
                "itinerarySummary": v.itinerary_summary,
                "visitedPorts": v.visited_ports,
                "visitedCountries": v.visited_countries,
                "cabinBooked": v.cabin_booked,
                "favouriteVenue": v.favourite_venue,
                "favouriteMemory": v.favourite_memory,
                "journalEntries": [
                    {
                        "entryId": j.entry_id,
                        "dateStr": j.date_str,
                        "voyageDayLabel": j.voyage_day_label,
                        "factualMilestoneSentence": j.factual_milestone_sentence,
                        "portOrSeaLocation": j.port_or_sea_location,
                    }
                    for j in v.journal_entries
                ],
                "status": v.status,
            }
            for v in profile.voyage_history
        ],
        "botWelcomeBackGreeting": profile.bot_welcome_back_greeting,
        "botClosingLogNote": profile.bot_closing_log_note,
        "proactiveMemoryInsights": memory_insights,
    }

    shipmate_ts_content = f"""// AUTO-GENERATED BY tools/generate_frontend_bridge.py
// DO NOT EDIT MANUALLY. SOURCE: BridgeMemoryEngine

export interface FavouritePlaceData {{
  locationId: string;
  name: string;
  category: string;
  shipName: string;
  deckLocation: string;
  whyFavoured: string;
}}

export interface ConfirmedHabitData {{
  habitId: string;
  category: string;
  observation: string;
  evidenceVoyage: string;
}}

export interface BridgeJournalEntryData {{
  entryId: string;
  dateStr: string;
  voyageDayLabel: string;
  factualMilestoneSentence: string;
  portOrSeaLocation: string;
}}

export interface CompletedVoyageLogData {{
  voyageId: string;
  shipName: string;
  cruiseLine: string;
  departureDate: string;
  itinerarySummary: string;
  visitedPorts: string[];
  visitedCountries: string[];
  cabinBooked: string;
  favouriteVenue: string;
  favouriteMemory: string;
  journalEntries: BridgeJournalEntryData[];
  status: string;
}}

export interface TravellerShipmateProfileData {{
  travellerName: string;
  totalVoyagesCount: number;
  totalSeaDays: number;
  visitedCountries: string[];
  visitedPorts: string[];
  visitedShips: string[];
  favouritePlaces: FavouritePlaceData[];
  confirmedHabits: ConfirmedHabitData[];
  voyageHistory: CompletedVoyageLogData[];
  botWelcomeBackGreeting: string;
  botClosingLogNote: string;
  proactiveMemoryInsights: string[];
}}

export const SHIPMATE_PROFILE_DATA: TravellerShipmateProfileData = {json.dumps(shipmate_payload, indent=2, ensure_ascii=False)};
"""
    with open(os.path.join(FRONTEND_GEN_DIR, "shipmate_memory.ts"), "w", encoding="utf-8") as f:
        f.write(shipmate_ts_content)
    print(f" [OK] Generated frontend/src/generated/shipmate_memory.ts for Shipmate Memory Logbook.")

    # 19. Generate Living Ship Digital Twin Engine
    from src.timonelo.database.living_ship_engine import (
        DigitalTwinEngine,
        OperationalStatus,
    )

    live_states = DigitalTwinEngine.list_all_live_states()
    live_payload = [
        {
            "shipName": ls.ship_name,
            "voyageTitle": ls.voyage_title,
            "currentStatus": ls.current_status.value,
            "currentLocation": ls.current_location,
            "currentSpeedKnots": ls.current_speed_knots,
            "weatherSummary": ls.weather_summary,
            "windForceBeaufort": ls.wind_force_beaufort,
            "seaStateDescription": ls.sea_state_description,
            "etaNextPort": ls.eta_next_port,
            "allAboardTime": ls.all_aboard_time,
            "gangwayOpen": ls.gangway_open,
            "operationalChanges": [
                {
                    "impactId": chg.impact_id,
                    "changeTitle": chg.change_title,
                    "rawMaritimeFact": chg.raw_maritime_fact,
                    "passengerTranslation": chg.passenger_translation,
                    "affectedServices": chg.affected_services,
                    "actionRequired": chg.action_required,
                    "recommendedAction": chg.recommended_action,
                    "evidenceSource": chg.evidence_source,
                }
                for chg in ls.operational_changes
            ],
            "botObservations": ls.bot_observations,
            "recommendedPassengerActions": ls.recommended_passenger_actions,
            "bridgeSignOff": ls.bridge_sign_off,
            "confidenceScore": ls.confidence_score,
        }
        for ls in live_states
    ]

    living_ship_ts_content = f"""// AUTO-GENERATED BY tools/generate_frontend_bridge.py
// DO NOT EDIT MANUALLY. SOURCE: DigitalTwinEngine

export interface OperationalImpactData {{
  impactId: string;
  changeTitle: string;
  rawMaritimeFact: string;
  passengerTranslation: string;
  affectedServices: string[];
  actionRequired: boolean;
  recommendedAction: string;
  evidenceSource: string;
}}

export interface LiveVoyageStateData {{
  shipName: string;
  voyageTitle: string;
  currentStatus: string;
  currentLocation: string;
  currentSpeedKnots: number;
  weatherSummary: string;
  windForceBeaufort: number;
  seaStateDescription: string;
  etaNextPort: string;
  allAboardTime: string | null;
  gangwayOpen: boolean;
  operationalChanges: OperationalImpactData[];
  botObservations: string[];
  recommendedPassengerActions: string[];
  bridgeSignOff: string;
  confidenceScore: number;
}}

export const LIVE_VOYAGE_STATES: LiveVoyageStateData[] = {json.dumps(live_payload, indent=2, ensure_ascii=False)};

export function getLiveVoyageStateByShip(shipName: string): LiveVoyageStateData {{
  const found = LIVE_VOYAGE_STATES.find((s) => s.shipName.toLowerCase().includes(shipName.toLowerCase()));
  return found || LIVE_VOYAGE_STATES[0];
}}
"""
    with open(os.path.join(FRONTEND_GEN_DIR, "living_ship.ts"), "w", encoding="utf-8") as f:
        f.write(living_ship_ts_content)
    print(f" [OK] Generated frontend/src/generated/living_ship.ts with {len(live_payload)} living digital twin states.")


if __name__ == "__main__":
    generate_bridge()
