#!/usr/bin/env python3
"""
Generate TypeScript Epistemic Canon Contracts from Python Canonical Models.
Governed by ADR-0002 and ADR-0003.
"""

from __future__ import annotations
import os
import sys
import inspect
from enum import Enum

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, REPO_ROOT)

from src.timonelo.ontology.models import (
    Method,
    Derivation,
    EvidenceCondition,
    HumanReviewState,
    PublishStatus,
    GeometryProvenance,
)

CANON_ENUMS = [
    ("Method", Method, "METHODS"),
    ("Derivation", Derivation, "DERIVATIONS"),
    ("EvidenceCondition", EvidenceCondition, "EVIDENCE_CONDITIONS"),
    ("HumanReviewState", HumanReviewState, "HUMAN_REVIEW_STATES"),
    ("PublishStatus", PublishStatus, "PUBLISH_STATUSES"),
    ("GeometryProvenance", GeometryProvenance, "GEOMETRY_PROVENANCES"),
]


def generate_ts_canon() -> str:
    lines = [
        "// AUTO-GENERATED BY tools/generate_epistemic_contract.py",
        "// DO NOT EDIT MANUALLY. SOURCE: src/timonelo/ontology/models.py",
        "// Governed by ADR-0002 (The Truth Model).",
        "",
    ]
    for type_name, enum_cls, const_name in CANON_ENUMS:
        members = [m.value for m in enum_cls]
        union_type = " | ".join(f"'{m}'" for m in members)
        lines.append(f"export type {type_name} = {union_type};")
        members_arr = ", ".join(f"'{m}'" for m in members)
        lines.append(f"export const {const_name}: readonly {type_name}[] = [{members_arr}] as const;")
        lines.append("")
    return "\n".join(lines)


def main():
    target_dir = os.path.join(REPO_ROOT, "frontend", "src", "generated")
    os.makedirs(target_dir, exist_ok=True)
    target_file = os.path.join(target_dir, "canon.ts")
    content = generate_ts_canon()
    with open(target_file, "w", encoding="utf-8") as f:
        f.write(content)
    print(f" [OK] Generated TypeScript canon contract: {os.path.relpath(target_file, REPO_ROOT)}")


if __name__ == "__main__":
    main()
