#!/usr/bin/env python3
"""Generate the canonical Markdown index for Timonelo knowledge records."""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path


METADATA_RE = re.compile(r"^-\s+([^:]+):\s*(.*)$")
LIST_ITEM_RE = re.compile(r"^\s*[-*+]\s+(.+?)\s*$")
ID_FIELDS = ("ID", "Entity ID", "Term ID", "Source ID")
TITLE_FIELDS = ("Canonical name", "Canonical term", "Title")
STATUS_FIELDS = ("Status", "Review status")
SKIPPED_NAMES = {"README.md", "CONTRIBUTING.md", "INDEX.md"}
SKIPPED_FOLDERS = {"templates", "images"}


@dataclass(frozen=True)
class Record:
    knowledge_id: str
    title: str
    category: str
    status: str
    folder: str
    source_count: int


def parse_sections(path: Path) -> tuple[str, dict[str, str], dict[str, list[str]]]:
    lines = path.read_text(encoding="utf-8").splitlines()
    title = ""
    metadata: dict[str, str] = {}
    sections: dict[str, list[str]] = {}
    current_section: str | None = None

    for line in lines:
        if line.startswith("# ") and not title:
            title = line[2:].strip()
        elif line.startswith("## "):
            current_section = line[3:].strip()
            sections.setdefault(current_section, [])
        elif current_section is not None:
            sections[current_section].append(line)

    for line in sections.get("Metadata", []):
        match = METADATA_RE.match(line)
        if match:
            metadata[match.group(1).strip()] = match.group(2).strip()
    return title, metadata, sections


def first_value(metadata: dict[str, str], fields: tuple[str, ...]) -> str:
    return next((metadata[field] for field in fields if metadata.get(field)), "")


def category_for(metadata: dict[str, str]) -> str:
    if metadata.get("Source ID"):
        return "Source"
    if metadata.get("Term ID"):
        return "Glossary"
    if metadata.get("Entity ID"):
        return metadata.get("Entity type") or "Entity"
    return metadata.get("Record type") or "Knowledge"


def count_sources(lines: list[str]) -> int:
    references = {
        match.group(1).strip()
        for line in lines
        if (match := LIST_ITEM_RE.match(line)) and match.group(1).strip()
    }
    return len(references)


def discover_records(root: Path) -> tuple[list[Record], list[str]]:
    records: list[Record] = []
    errors: list[str] = []

    for path in sorted(root.rglob("*.md")):
        relative = path.relative_to(root)
        if path.name in SKIPPED_NAMES or relative.parts[0] in SKIPPED_FOLDERS:
            continue

        heading, metadata, sections = parse_sections(path)
        knowledge_id = first_value(metadata, ID_FIELDS)
        title = first_value(metadata, TITLE_FIELDS) or heading
        status = first_value(metadata, STATUS_FIELDS)
        missing = [name for name, value in (("Knowledge ID", knowledge_id), ("Title", title), ("Status", status)) if not value]
        if missing:
            errors.append(f"{relative.as_posix()}: missing {', '.join(missing)}")
            continue

        records.append(Record(
            knowledge_id=knowledge_id,
            title=title,
            category=category_for(metadata),
            status=status,
            folder=relative.parent.as_posix(),
            source_count=count_sources(sections.get("Sources", [])),
        ))

    records.sort(key=lambda record: (record.knowledge_id.casefold(), record.folder, record.title.casefold()))
    return records, errors


def escape(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def render(records: list[Record]) -> str:
    lines = [
        "# Knowledge Index",
        "",
        "<!-- Generated by tools/generate_knowledge_index.py. Do not edit manually. -->",
        "",
        "| Knowledge ID | Title | Category | Status | Folder | Source Count |",
        "| --- | --- | --- | --- | --- | ---: |",
    ]
    lines.extend(
        "| " + " | ".join(escape(value) for value in (
            record.knowledge_id,
            record.title,
            record.category,
            record.status,
            record.folder,
            record.source_count,
        )) + " |"
        for record in records
    )
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    repository_root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--knowledge-dir", type=Path, default=repository_root / "knowledge")
    parser.add_argument("--output", type=Path)
    parser.add_argument("--check", action="store_true", help="fail if the existing index is stale")
    args = parser.parse_args(argv)

    knowledge_root = args.knowledge_dir.resolve()
    output = args.output.resolve() if args.output else knowledge_root / "INDEX.md"
    if not knowledge_root.is_dir():
        print(f"Knowledge index generation: FAIL\nKnowledge directory does not exist: {knowledge_root}")
        return 1

    try:
        records, errors = discover_records(knowledge_root)
    except (OSError, UnicodeError) as exc:
        print(f"Knowledge index generation: FAIL\nCannot read knowledge repository: {exc}")
        return 1
    if errors:
        print("Knowledge index generation: FAIL")
        for error in errors:
            print(f"- {error}")
        return 1

    content = render(records)
    if args.check:
        current = output.read_text(encoding="utf-8") if output.exists() else ""
        if current != content:
            print("Knowledge index check: FAIL\nknowledge/INDEX.md is missing or stale.")
            return 1
        print(f"Knowledge index check: PASS\nIndexed {len(records)} record(s).")
        return 0

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(content, encoding="utf-8", newline="\n")
    print(f"Knowledge index generation: PASS\nIndexed {len(records)} record(s) in {output}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
